### ISSUE TITLE
maximumWaitingRuns add to designer GUI

### ISSUE THREAD

**Issue by john-long2** [Azure/LogicAppsUX#4927] opened 2024-06-02 14:31 UTC
### Describe the Bug with repro steps

https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-workflow-actions-triggers#runtime-config-options

Some of our Logic Apps error when reading messages off a service bus queue as they are "waiting" longer than the max lock duration on the topics subscription settings (5 minutes).

We have resolved this by setting the maximumWaitingRuns to 1,

"runtimeConfiguration": {
                    "concurrency": {
                        "maximumWaitingRuns": 1,
                        "runs": 10
                    }
                },
                "type": "ServiceProvider"
            }

![image](https://github.com/Azure/LogicAppsUX/assets/104009538/cc073330-4ce1-4991-a1fd-46c9362daa09)

However this can only be set in code view.  If any makes a change ion the designer and saves the workflow this setting isa lost.  Please could this be added to the GUI as it is a really useful feature.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

edge

**Comment by Eric-B-Wu** [comment] 2024-06-11 09:36
Closing as a duplicate of https://github.com/Azure/LogicAppsUX/issues/4927, given that we're seeing more customers want this, I'm gonna go ahead and see if this can be implemented

**Closed by Eric-B-Wu** 2024-06-11 09:36 UTC
Labels: Feature Request
