### ISSUE TITLE
Logic app UX removing additional fields for JIRA connector

### ISSUE THREAD

**Issue by pradeepsj7** [Azure/LogicAppsUX#5248] opened 2024-08-01 12:39 UTC
### Describe the Bug with repro steps 

As new additional fields are added in the JIRA connectors, are been removed after refresh both from the code view and design view

New Design

![image](<https://github.com/user-attachments/assets/47173c2d-4e4a-4b37-af96-23283d830f8a>)

Legacy design holds the description field value

![image](<https://github.com/user-attachments/assets/3fbd1f59-db93-47ec-84f7-7677b6786467>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-08-01 16:32
Hi @pradeepsj7, this is a duplicate of the following issue: https://github.com/Azure/LogicAppsUX/issues/5129
This fix should be going out with our next release, finishing all regions by the 16th.
The issue is that when initializing designer we are missing those parameter values, so if you make the change in code view and save, it should work as expected until you save over it with designer.

**Closed by rllyy97** 2024-08-01 16:32 UTC
