### ISSUE TITLE
When making a quick-change SQL actions may lose fields

### ISSUE THREAD

**Issue by bwelmers** [Azure/LogicAppsUX#6015] opened 2024-11-01 14:12 UTC
### Describe the Bug with repro steps 

Sometimes when saving a larger LogicApp the SQL statement lose their field actions (in the code the Body statement gets removed).

This has been noticed over the last month 3 or 4 times. So, it is not happening consistently, but it is occurring and causing our company issues. We have narrowed it down to quick changes cause the issue. So, these reproduction steps seem to be what is happening:

1. Have a logic app with many actions including some MS SQL V2 actions (Insert row v2 or Update row (V2)) 
2. open the logic app make a quick change to any action 
3. save the logic app 
4. exit out of the logic app 
5. go back into the logic app 
6. the fields in the Insert Row or Update Row statements are missing 

The Logic app that is used as an example is one of 3 or 4 logic apps that we have found this issue. It just is the most recently example of the issue.

It feels like the issue is front end issue, where the SQL actions do not update quick enough on the screen. While they are still updating the LogicApp is saved removing the body of the SQL actions.

I have not seen any error messages associated with this issue.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

Version 10/29/2027 7:59 am

### Screenshots or Videos 

Working JSON of the logic app is provided in the Workflow JSON box.

I went into the Logic App and edited this select query

Original version

`"query": "SELECT [userPrincipalName]\n ,[CompEmpKey]\n FROM [dbo].[ADUsers_ALL]\nwhere Enabled = 'True'\nand Employment_Status in ('S','P','A','W','N','M')\n-- and Cost_Center = '6301000' -- random cost center to test people in and out of the table\n--and created &amp;gt;= getdate()-2"`

Edited Version

`"query": "SELECT [userPrincipalName]\n ,[CompEmpKey]\n FROM [dbo].[ADUsers_ALL]\nwhere Enabled = 'True'\nand Employment_Status in ('S','P','A','W','N','M')\n-- and Cost_Center = '6301000' -- random cost center to test people in and out of the table\n--and created &amp;gt;= getdate()-2\nand userPrincipalName = 'kkeener@davishelliot.com'"`

then saved the logic app.

The next time I ran it I got some errors and found that there were a number of SQL statements that had no information anymore

Which caused this statement

`"Insert_row_(V2)_into_Proactive_Teams_Messages": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "body": { "userPrincipalName": "@item()?['userPrincipalName']", "created": "@utcNow()", "Modified": "@utcNow()", "CompEmpKey": "@item()?['CompEmpKey']", "ChatType": "@body('Parse_JSON_get_chat_ID')?['chatType']", "TeamsChatId": "@body('Parse_JSON_get_chat_ID')?['id']", "tenant": "@variables('varTenantID')", "BotID": "@variables('varBotClientID')" }, "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[Proactive_Teams_Messages]'))}/items" },`

to change into this statement

`"Insert_row_(V2)_into_Proactive_Teams_Messages": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "body": { "userPrincipalName": "", "created": "", "Modified": "" }, "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[Proactive_Teams_Messages]'))}/items" },`

also this statement

`"Insert_row_logic_app_runtime_log_success": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "body": { "LogicAppName": "Notifications_Get_ChatID", "StartTimeUTC": "@variables('varStartTime')", "EndTimeUTC": "@utcNow()", "Message": "Success", "LogicApp_RunID": "@workflow().run.name", "Platform": "Logic Apps" }, "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[LogicAppRunTimeLog]'))}/items" },`

changed to this:

`"Insert_row_logic_app_runtime_log_success": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[LogicAppRunTimeLog]'))}/items" },`

and this one

`"Insert_row_logic_app_run_time_log_Failure": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "body": { "LogicAppName": "Notifications_Get_ChatID", "StartTimeUTC": "@variables('varStartTime')", "EndTimeUTC": "@utcNow()", "Message": "Failure", "LogicApp_RunID": "@workflow().run.name", "Platform": "Logic Apps" }, "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[LogicAppRunTimeLog]'))}/items" } } },`

changed to this

`"Insert_row_logic_app_run_time_log_Failure": { "type": "ApiConnection", "inputs": { "host": { "connection": { "name": "@parameters('$connections')['sql-2']['connectionId']" } }, "method": "post", "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/tables/@{encodeURIComponent(encodeURIComponent('[dbo].[LogicAppRunTimeLog]'))}/items" } } },`

screen shot of one of the changed statments

![Image](<https://github.com/user-attachments/assets/2f659b4f-8dc1-42f1-b8a1-0c5af25ddf65>)

Here are the old and new versions of this logic app. These were saved 5 minutes apart.

[Older good version.json](<https://github.com/user-attachments/files/17602650/Older.good.version.json>)

[Newer version missing pieces.json](<https://github.com/user-attachments/files/17602649/Newer.version.missing.pieces.json>)

### Browser 

Edge on Windows 11

Microsoft Edge for Business

[Learn more about Microsoft Edge for Business](<https://go.microsoft.com/fwlink/?linkid=2244048>)

Version 130.0.2849.56 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by hartra344** [comment] 2024-11-11 19:55
I removed the workflow json from your post because it got flagged for having an AAD client secret embedded. I would suggest rotating that secret if you haven't already.

**Comment by bwelmers** [comment] 2024-11-11 19:59
Thanks, I did go through the JSON after I saw that message and changed the secret. I also removed it from the two downloads.

I forgot I had that in the workflow :(

**Comment by rllyy97** [comment] 2024-11-12 16:28
This looks like a duplicate of https://github.com/Azure/LogicAppsUX/issues/5937
I'm going to close this but you can track progress on the linked issue report

**Closed by rllyy97** 2024-11-12 16:28 UTC
