### ISSUE TITLE
Standard: Environment variables blade missing

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3523] opened 2023-10-25 16:13 UTC
### Describe the Bug with repro steps

1. Create a logic app
2. Search for Environment variables blade

**Expected:**Environment variables blade should be present.
**Actual:**Environment variables blade missing

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/2d8cbd20-edf0-4c84-84e6-79d0fb4df9aa)

### Browser

Edge

### Additional context

@rllyy97 Missing this blade in production environment as well.

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd2594ae14f444c61261f08dbd56ffed4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638338449531714964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rGYtZR1ZaGE5PItRTFq0Z05JfEHsbfbTmGvHZYFWnQE%3D&reserved=0) 
Version:  2.31023.1.1

AB#25594543

**Comment by rllyy97** [comment] 2023-10-25 16:23
After some initial investigation it appears that this wasn't caused by an issue in our portal code.
Last week's testing was done on 2.31010.1.2 without issue, and the changes made between then and 2.31010.1.5 all seem unrelated.

**Comment by rllyy97** [comment] 2023-10-25 17:51
I've talked with App Service team and they are working on a fix, for mitigation doing a hard refresh of the page should make the `Environment Variables` blade menu item appear.

**Comment by rllyy97** [comment] 2023-11-06 20:47
Closing as this has been resolved

**Closed by rllyy97** 2023-11-06 20:47 UTC
