### ISSUE TITLE
Save Button doesn't work

### ISSUE THREAD

**Issue by cagrimunyas** [Azure/LogicAppsUX#2329] opened 2023-05-10 22:29 UTC
### Describe the Bug with repro steps

In the preview UI when hit on save, changes saved appears however while leaving the page warning is thrown saying unedited changes will be deleted and the changes are not saved after all. 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
//Includes confidential info & API keys.
```

### Browser

Chrome on Mac OS 13.3.1

**Comment by hartra344** [comment] 2023-05-10 22:48
Thank you for reporting the issue. This is duplicate of #2041, so closing htis one just because we're tracking it there.

**Closed by hartra344** 2023-05-10 22:48 UTC
Labels: duplicate, Consumption, Saving Issues
