### ISSUE TITLE
In Azure Automation connector,  Managed ID disabled, renderComponentIntoRoot Error occurs in Consumption Preview Designer 

### ISSUE THREAD

**Issue by nobuko-yamada** [Azure/LogicAppsUX#3962] opened 2024-01-10 07:31 UTC
### Describe the Bug with repro steps 

![image](<https://github.com/Azure/LogicAppsUX/assets/115044612/4bb6599b-a528-4b85-b6a1-adcb585aecb6>)

Check Managed Id is off. 

![image](<https://github.com/Azure/LogicAppsUX/assets/115044612/dd1d15ee-bf53-46a9-82ff-697c8ab1c8e2>)

Search Azure Automation Connector

![image](<https://github.com/Azure/LogicAppsUX/assets/115044612/007180a8-8150-4c8b-ae97-5ea6d2f09a10>)

Error occurs.

![image](<https://github.com/Azure/LogicAppsUX/assets/115044612/3c3f6633-db82-4055-8500-a65e6eb0c8d7>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome, Edge

### Additional context 

*No response*

**Comment by erottier** [comment] 2024-01-10 14:28
I know I'm using Intune, but the error is kinda of the same.
Both the renderComponentIntoRoot component and a .ReactView content.

Are these related?

![Intune_renderComponentIntoRoot_error](https://github.com/Azure/LogicAppsUX/assets/25172811/b25caf6f-661f-4035-a7a4-2c4f5c2ac5a0)

**Comment by hartra344** [comment] 2024-01-10 21:24
@erottier this is an entirely different project team, looks like it's coming from the Active Directory team. So I won't be able to help with that one.

@nobuko-yamada if you open up dev tools as described in teh TSG, are you able to see any errors in the console. I'm not able to repro the problem with the steps you provided.

**Comment by nobuko-yamada** [comment] 2024-01-10 22:06
Thank you so much for the comments @hartra344 !
Here is the log.
[portal.azure.com-1704924231341.log](https://github.com/Azure/LogicAppsUX/files/13894996/portal.azure.com-1704924231341.log)

And I can see the error in network tab.
![image](https://github.com/Azure/LogicAppsUX/assets/115044612/05c101f7-7462-4aff-a631-798db729e16d)

**Comment by erottier** [comment] 2024-01-11 15:09
> @erottier this is an entirely different project team, looks like it's coming from the Active Directory team. So I won't be able to help with that one.

I know, but if it's an error in the underlying components it could be good to have more angles to look at an issue right? Anyway, Microsoft is one big company right? I would think things have a shared codebase and fixing underlying tech would fix issues in multiple products.

Why brush something aside so quickly when it could give extra insight?

**Comment by hartra344** [comment] 2024-01-11 17:48
> > @erottier this is an entirely different project team, looks like it's coming from the Active Directory team. So I won't be able to help with that one.
> 
> I know, but if it's an error in the underlying components it could be good to have more angles to look at an issue right? Anyway, Microsoft is one big company right? I would think things have a shared codebase and fixing underlying tech would fix issues in multiple products.
> 
> Why brush something aside so quickly when it could give extra insight?

This is just an error that's given anytime the javascript crashes in the portal, in this case likely for very different reasons. The code itself isn't actually shared at all here. I'm not trying to brush it aside, just making it clear that fixing this issue won't fix that issue and you may need to open a support case to get help from them since I don't know if they have an open issue board like this one.

**Comment by rllyy97** [comment] 2024-02-08 20:36
Closing issue, this is a duplicate of https://github.com/Azure/LogicAppsUX/issues/3669,
I'm working on #3669 and will give updates there.

**Closed by rllyy97** 2024-02-08 20:36 UTC
Labels: Bug
