### ISSUE TITLE
Boolean dynamic content is converted to string and uppercase in shared connectors

### ISSUE THREAD

**Issue by cmeadowstech** [Azure/LogicAppsUX#2462] opened 2023-05-19 20:33 UTC
### Describe the Bug with repro steps

When a shared connector uses dynamic content of the boolean data type, it stringifies the value and converts it to uppercase. For example, true will be converted to 'True'

Repro.

1. Create a boolean variable with a initial value of true
2. Add a send data or create blob action and use the above boolean variable as part of the content
3. Run the flow and check the raw inputs of the blob action, you will see 'True', instead of the expected 'true'
4. See video below as an example

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Initialize_variable": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "testBoolean",
              "type": "boolean",
              "value": true
            }
          ]
        },
        "runAfter": {}
      },
      "Send_Data": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": "azureloganalyticsdatacollector"
            }
          },
          "method": "post",
          "body": "{\n\"test\": @{variables('testBoolean')}\n}",
          "headers": {
            "Log-Type": "testLog"
          },
          "path": "/api/logs"
        },
        "runAfter": {
          "Initialize_variable": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "When_a_HTTP_request_is_received": {
        "type": "Request",
        "kind": "Http"
      }
    }
  },
  "connectionReferences": {
    "azureloganalyticsdatacollector": {
      "connection": {
        "id": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/connections/azureloganalyticsdatacollector"
      },
      "connectionName": "azureloganalyticsdatacollector",
      "api": {
        "id": "/subscriptions/{subscriptionId}/providers/Microsoft.Web/locations/eastus/managedApis/azureloganalyticsdatacollector"
      },
      "authentication": {
        "type": "ManagedServiceIdentity"
      }
    }
  },
  "parameters": {}
}
```

### Screenshots or Videos

![booleanBug](https://github.com/Azure/LogicAppsUX/assets/30964870/acad9444-116a-4458-9e3b-d74c85e60c4a)

![image](https://github.com/Azure/LogicAppsUX/assets/30964870/2d2bb7e6-66ce-43d5-9667-71a0608fe5c7)

![image](https://github.com/Azure/LogicAppsUX/assets/30964870/7ae45413-a1c9-4139-95c4-aa8197847fe1)

![image](https://github.com/Azure/LogicAppsUX/assets/30964870/916bec5f-725d-47b4-bebb-fddca05fcaab)

### Browser

Edge

**Comment by preetriti1** [comment] 2023-05-20 00:31
@cmeadowstech - The JSON request body field you have in send data is of type string, and if you input any dynamic content of any type (boolean here), it is going to stringify it, 
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/683949d6-84c1-47f7-9bce-b6c41e0e9404)

The code view also indicates you have `"body": "{\n\"test\": @{variables('testBoolean')}\n}",`

So closing this as not a bug.

**Closed by preetriti1** 2023-05-20 00:31 UTC
