### ISSUE TITLE
New Logic Apps designer UI - Init activity for Object type variables fails at runtime

### ISSUE THREAD

**Issue by meadows-st-Techlytical** [Azure/LogicAppsUX#4659] opened 2024-04-19 18:33 UTC
### Describe the Bug with repro steps

In the legacy UI, you could create a JSON Object variable (via the Init Variable activity) directly in the UI.

When you edit any activity using the new designer UI (which Azure switched us to in our tenant now by default without any activity on my part) and you have used the Init activity to create a JSON object variable, at run time the system throws a fatal error indicating that you can't assign a string to an "Object" variable.

To work around this issue, you have to convert the Init activity using the Code view.  I have not yet found a way to create the object in the Init activity using the UI - even though the compiler/interpreter does not throw an error.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
// If you use the following in the Legacy Designer UI (code view), then attempt to switch to the New Designer UI and merely save in the New Designer (not in Code view), the "value" element will be converted to a string without any user interaction (other than clicking save)
// NOTE: this same behaviour also appears to affect any other variable types (like Float and Int) that are initialized with a value using the Legacy Designer UI.
{
  "type": "InitializeVariable",
  "inputs": {
    "variables": [
      {
        "name": "objTESTING",
        "type": "object",
        "value":{
           "Test1b": "Test1b Value",
           "Test1a": "Test1a Value",
           "Comment": "This approach works in the legacy designer UI."
      }
  },
  "runAfter": {
    "DelayToPreventLocking": [
      "Succeeded"
    ]
  }
}
```

### Screenshots or Videos

Legacy Designer UI:
![image](https://github.com/Azure/LogicAppsUX/assets/131618839/a8396f02-6474-4613-9279-96ac5572136c)

Resulting Code using legacy UI:
![image](https://github.com/Azure/LogicAppsUX/assets/131618839/196912ca-29f3-4542-8c82-8d850abd93ca)

New Designer UI:
![image](https://github.com/Azure/LogicAppsUX/assets/131618839/0d90f3c7-8909-45e1-a5e5-602c8178eff5)

Resulting Code from New Designer UI:
![image](https://github.com/Azure/LogicAppsUX/assets/131618839/efeeb096-84d1-46b5-acad-5d6ff373c964)

### Browser

Edge

### Additional context

I discovered this issue while debugging a newly discovered error in a workflow that I had not edited in several months but I had created using the Legacy Designer UI.  In the interim, it appears that the tenant in which this Logic App exists has been converted to use the new designer UI by default (I did not knowingly make any changes that would turn the new designer on by default).  I thus used the new designer UI to make a 1-line edit to an unrelated activity and after saving (which of course did not indicate any errors) when I attempted to run the Logic App workflow, I immediately received the error that an Object variable cannot be initialized from a String.

**Comment by hartra344** [comment] 2024-04-23 12:44
Are you still able to repro this in production right now? I am trying to follow your exact steps but it's working perfectly well.

Also, yes, new designer is currently the GA version of designer, Legacy Designer is still available for those that have trouble with anything in the new designer while we iron those out but it will be going away in the future.

**Comment by meadows-st-Techlytical** [comment] 2024-04-23 13:29
I did notice one additional issue though that may be related to the same issue...

When I attempt to edit an Object variable's initial value using the New Designer (after the Logic App was created using the Legacy Designer and then manually selected New Designer), I receive an error message "enter a valid number" when I click out of the "Value" field.

Logic app in New Designer after manually converting/enabling from Legacy Designer:
![2024-04-23 09_23_07-TCIDemoObjVariableIssue - Microsoft Azure and 23 more pages - Techlytical - Micr](https://github.com/Azure/LogicAppsUX/assets/131618839/f464514c-91c6-4c04-a3f2-05f284e089e9)

Then I attempt to make a manual change to the initial value in the "Parameters" tab (then clicking anywhere out of the edit box):
![2024-04-23 09_19_04-TCIDemoObjVariableIssue - Microsoft Azure and 23 more pages - Techlytical - Micr](https://github.com/Azure/LogicAppsUX/assets/131618839/ffd7d897-1039-4af4-9e84-1d2bf247c3da)

And when I click on the "Errors" menu item:
![2024-04-23 09_19_25](https://github.com/Azure/LogicAppsUX/assets/131618839/22d7f56b-e031-4922-b941-410621ceda1c)

The edited Logic App will no longer run and I cannot save it without correcting the "Error"

**Comment by Eric-B-Wu** [comment] 2024-04-23 15:24
@meadows-st-Techlytical would you be able to check the extension version that you're currently on following this steps: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#finding-your-session-id-or-portal-extension-version? There was a bug that was there last week, but we've since hotfixed it in 2.40408.1.6 which I'm still seeing in your screenshots

**Comment by meadows-st-Techlytical** [comment] 2024-04-23 15:42
![2024-04-23 11_39_57-TCIDemoObjVariableIssue - Microsoft Azure and 24 more pages - Techlytical - Micr](https://github.com/Azure/LogicAppsUX/assets/131618839/25cd8e41-1d56-4702-9182-99c1a9484697)

It looks like my session is only on 240408.1.5

**Comment by Eric-B-Wu** [comment] 2024-04-23 15:49
Alright perfect, I'm going to close this issue now. Thank you for the detailed report and apologies for the regression.

**Closed by Eric-B-Wu** 2024-04-23 15:49 UTC
