### ISSUE TITLE
[Power Automate] Outlook attachments should support complete name/bytes structure

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2049] opened 2023-04-17 23:01 UTC
### Describe the Bug with repro steps

https://msazure.visualstudio.com/One/_workitems/edit/17785114

### Browser

Chrome

**Comment by hartra344** [comment] 2023-04-17 23:04
Duplicate of #1948 and tracked by #1996

**Closed by hartra344** 2023-04-17 23:04 UTC
Labels: duplicate
