### ISSUE TITLE
Cannot select tenant when creating connection to azure resources with OAuth

### ISSUE THREAD

**Issue by jesseck3013** [Azure/LogicAppsUX#4993] opened 2024-06-18 05:55 UTC
### Describe the Bug with repro steps 

On generally available designer, there is no way to select tenant.

![image](<https://github.com/Azure/LogicAppsUX/assets/143072221/a876dbab-ff38-4b95-9dc0-2919f8f9e183>)

On legacy designer, there is an option to select tenant.

![image](<https://github.com/Azure/LogicAppsUX/assets/143072221/b3bcdf08-c630-4dc4-907b-6698900d0710>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge Version 126.0.2592.56 (Official build) (64-bit)

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-06-18 18:53
Hi @jesseck3013, thanks for the bug report!  This looks like a duplicate of the following issue: https://github.com/Azure/LogicAppsUX/issues/4449
I'm going to close this copy, but I'm starting work on a fix today, so you can find updates as I have them on the other issue.  
I will give an update with an ETA as soon as I can!

**Closed by rllyy97** 2024-06-18 18:53 UTC
