### ISSUE TITLE
Data Mapper cannot find schemas if folder structure is not the default

### ISSUE THREAD

**Issue by karlrissland** [Azure/LogicAppsUX#3393] opened 2023-09-28 16:04 UTC
### Describe the Bug with repro steps

Repo structure is as follows:
- .vscode
- docs
- infra
- src
- readme.md

Created logicapp inside src folder.

Open vs code in root of repo.

Workflow designer can find the schemas without issue when using a schema validation action.

Data mapper cannot find any schemas.

When I open vs code within the src folder and open data mapper, it is able to find the schemas.

I am able to run and debug the logicapp when opening vscode from the root without issue.

### Screenshots or Videos

running vs code at the root of the repo, data mapper cannot find the schemas
![image](https://github.com/Azure/LogicAppsUX/assets/9871029/d3dfd408-33f3-4343-acde-9bd2e9e75931)

open vs code in the src folder and it works as expected
![image](https://github.com/Azure/LogicAppsUX/assets/9871029/830bef19-31a9-4885-9af7-d82435ebe35d)

### Version

2.70.1

### Additional context

When using logic app standard, I typically have other artifacts that are included with the project... documentation, infrastructure as code, etc.  Also may have functions, containers, etc. in my project.  I do use .code-workspace files but didn't think it was needed in this case since it is just a logic app and an arbitrary folder structure that allowed me to run and debug the logic app and the workflow designer functioned correctly.

AB#25304306

**Comment by hartra344** [comment] 2023-10-18 18:08
Closing this as a duplicate of #3393

**Closed by hartra344** 2023-10-18 18:08 UTC
Labels: Data Mapper
