### ISSUE TITLE
SharePoint Get File Content Action Not Working as Designed

### ISSUE THREAD

**Issue by brian-custer** [Azure/LogicAppsUX#2742] opened 2023-06-14 13:26 UTC
### Describe the Bug with repro steps

Drag a SharePoint get file content action to the canvas and set parameters to variables from previous actions and then click save. An error appears stating Workflow validation failed for the workflow ''. {"error":{"code":"BadRequest","message":"The API connection name must be provided in the 'Get_file_content' action inputs."}}. 

My question is why am I getting this error when I have supplied the required parameters with variable values? It is preventing me from completing my workflow.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/113911924/ddd69912-adcc-4463-9b50-dce531e2664b)

### Browser

Edge

### Additional context

The action worked fine in VS Code although I couldn't debug it so I put it in the portal designer and experienced this problem.

AB#24269631

**Comment by preetriti1** [comment] 2023-06-14 20:52
It seems the drag and drop might have caused some issue here. @Eric-B-Wu can you take a look?

**Comment by rllyy97** [comment] 2023-06-29 18:45
Hi @brian-custer, thanks for the bug report!  The root of your issue appears to be a duplicate of this issue: https://github.com/Azure/LogicAppsUX/issues/2837
We've merged a fix and it will be rolling out through next week, finishing on July 7th.
If you're still experiencing your issue after the 7th let us know and we'll take another look at it!

**Closed by rllyy97** 2023-06-29 18:45 UTC
Labels: Consumption

**Comment by brian-custer** [comment] 2023-06-29 18:46
Sounds good.

Brian Custer
206-661-2674
________________________________
From: Riley Evans ***@***.***>
Sent: Thursday, June 29, 2023 11:45:16 AM
To: Azure/LogicAppsUX ***@***.***>
Cc: Brian Custer ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL - Re: [Azure/LogicAppsUX] SharePoint Get File Content Action Not Working as Designed (Issue #2742)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #2742<https://github.com/Azure/LogicAppsUX/issues/2742> as completed.
