### ISSUE TITLE
Logic Apps "Preview Designer" is missing Run button

### ISSUE THREAD

**Issue by artemt-yavica** [Azure/LogicAppsUX#3768] opened 2023-11-29 08:55 UTC
### Describe the Bug with repro steps

Edit any Logic App
Switch to the new designer by clicking "Try Preview Designer" button
Try to run your Logic App -> you can't

There is no Run Trigger button in the new designer.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![NewDesigner](https://github.com/Azure/LogicAppsUX/assets/117354593/70e421c0-197e-4db4-9035-8563a0170745)
![OldDesigner](https://github.com/Azure/LogicAppsUX/assets/117354593/209972ec-44dd-4df9-abd0-fe9b8da038db)

### Browser

Chrome latest version

AB#25990733

**Comment by hartra344** [comment] 2023-11-29 15:30
duplicate of #2790

**Closed by hartra344** 2023-11-29 15:30 UTC
Labels: Consumption, triage
