### ISSUE TITLE
Schema validation error with "Parse JSON"  action does not show details

### ISSUE THREAD

**Issue by janikarkkainen** [Azure/LogicAppsUX#6060] opened 2024-11-09 10:12 UTC
When using Parse JSON action and it fails due to schema validation I can't see any error details on which property the validation fails.

Error message used to be more detailed in previoys versions of Logic Apps UI.

The generic error message I get is:

*ValidationFailed The schema validation failed.*

**Comment by ccastrotrejo** [comment] 2024-11-11 19:01
Hi @janikarkkainen thanks for raising this issue. 
Could you please provide us an example in which the Parse JSON action shows a more explicit error? Maybe if we can get your workflow json or an example of the expected schema vs the schema that got into the action. 

I gave it a try and for now the error looks the same. You can click in `Show raw outputs` for a more detail error

![Image](https://github.com/user-attachments/assets/ac11a2ec-6032-46a2-8f53-32c7ccf504f8)

![Image](https://github.com/user-attachments/assets/0e917b71-4cbc-430f-8437-98dc36a438a4)

**Comment by ccastrotrejo** [comment] 2024-11-12 19:38
Hi @janikarkkainen thanks for raising this issue. I will close this issue as this is expected by design. As we stated on the PR https://github.com/Azure/LogicAppsUX/pull/5723
As for now we are relying on the schema of every action itself to show the outputs and inputs. For now you can keep looking at the more detailed outputs in the `Show raw outputs` section

**Closed by ccastrotrejo** 2024-11-12 19:38 UTC

**Comment by janikarkkainen** [comment] 2024-11-13 08:28
Hi, thanks for resolving this.

I do see detailed error message when clicking "Show raw outputs", which was not expected because the output area says "No outputs", which is a bit misleading. See my screenshot below.

![Image](https://github.com/user-attachments/assets/7e94526e-f1f4-4962-a6d2-5acab91daacf)

Btw, for me the Raw outputs Window opens in a separate blade instead of how it looks in your screenshot.

![Image](https://github.com/user-attachments/assets/38b644e3-021f-4e9c-8f51-97be04c118e8)

**Comment by janikarkkainen** [comment] 2024-11-14 08:03
Hi, I understand that it is the expected behavior and my problem has been solved.

However, it's still a bit misconfusing because it explicitly says "No outputs" while there is an output when clicked "Show raw outputs".

**Comment by ccastrotrejo** [comment] 2024-11-14 14:54
Hi @janikarkkainen we clearly understand the confusion this can cause as it clearly states that there are no outputs. 
As for now this will stay the same as we are looking forward to a more dynamic and less hardcoding way of loading the outputs and errors in actions. I will keep an eye on these kinds of issues, and I will add an item to our list of designer improvements to triage it.
