### ISSUE TITLE
Issue - Substring "Start Index" input from Subtract function shows type validation error 

### ISSUE THREAD

**Issue by kewear** [Azure/LogicAppsUX#2316] opened 2023-05-10 16:43 UTC
### Describe the Bug with repro steps

Substring "Start Index" input from Subtract function shows type validation error 

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/83832436/e0860732-aed0-4b96-8f76-1dc22997b40b)

### Version

2.15.15

### Additional context

More info in internal OneNote

AB#25101081

**Comment by refortie** [comment] 2023-05-11 18:06
This is technically by design. The Substring index value is a "integer" and the result of a subtract is a "number" type. I don't want to close this yet as I think there needs to be a larger conversation around number types.

**Closed** 2023-09-13 19:08 UTC
Labels: Data Mapper
