### ISSUE TITLE
Unable to look into the next iteration in a foreach loop of Logic App's run instance

### ISSUE THREAD

**Issue by gkumaequinor** [Azure/LogicAppsUX#5582] opened 2024-09-03 14:06 UTC
### Describe the Bug with repro steps 

Open the Logic App run instance.

 Go to the Foreach loop.

 Click on the Next iteration in the loop.

 As soon as you scroll the page , the loop gets back to 1st iteration irrespective of what you have selected.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-09-03 16:05
Hi @gkumaequinor, this is a duplicate of the following issue: https://github.com/Azure/LogicAppsUX/issues/5530
I am going to close this issue, please follow the other for any progress updates, I'll be working on this issue today

**Closed by rllyy97** 2024-09-03 16:05 UTC
