### ISSUE TITLE
Connection Cancel button

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2900] opened 2023-07-03 11:45 UTC
### Describe the Bug with repro steps

1.Create a Logic app in Standard portal and add stateful workflow.
2.Add http trigger and add azure function and create the connection for function.
3.Before filling the values and saving, click on CREATE NEW connection.
4.Now again we are at step2. Do not select any function and try to use cancel button.

**Expected:** After clicking on cancel button it should go to last created connection page.

**Actual:** Not as expected, Resist on same page after using cancel button.
![image](https://github.com/Azure/LogicAppsUX/assets/92098490/10f89db7-8859-419c-9cee-6fe9120cc827)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

### Additional context

**Environmental Details:**

**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-prakumar%40microsoft.com%7C8fba17541dec415bd2b308db7ba263b8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638239709652261160%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F4Dz7qewvxq8uJPqGJ0diYsyQ2IMx1B3g13tLK40CQQ%3D&reserved=0)

**Version:** 2.30701.1.1

AB#24437886

**Comment by rllyy97** [comment] 2023-07-10 15:16
This looks to be a duplicate of this issue: https://github.com/Azure/LogicAppsUX/pull/2890
We are currently rolling out the fix for this and it should be live for all regions on July 11th

**Closed by rllyy97** 2023-07-10 15:16 UTC
Labels: Found By Testers

**Comment by vgouth** [comment] 2023-07-21 07:31
Issue **not** repro in the latest portal request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Ccaeede01bc6247df730608db899fa56e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255091053826394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkVfWg4QCG8m1pHWR2lnWsaUSDKt3WPkUseVXK7UwVY%3D&reserved=0)
**Version:** 2.30717.1.1
