### ISSUE TITLE
Cannot start Workflow designer due to framework error

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#3899] opened 2023-12-21 13:49 UTC
### Describe the Bug with repro steps

1. Configure VS Code and extension in "run as admin" mode.
2. Create a new stateful workflow using extension functionality.
3. Get this error:

```txt
Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

[2023-12-21T12:57:23.413Z] Error configuring services in an external startup class.
[2023-12-21T12:57:23.413Z] Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2023-12-21T12:57:23.436Z] A host error has occurred during startup operation 'e15f466b-9a32-4cf6-8333-1c9a716257ab'.
[2023-12-21T12:57:23.436Z] Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.Workflows.WebJobs.Extensions: Could not load type 'Microsoft.Azure.WebJobs.Host.Listeners.IListenerDecorator' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Value cannot be null. (Parameter 'provider')
[2023-12-21T12:57:23.448Z] Host startup operation has been canceled
[2023-12-21T12:57:23.463Z] Azure Storage connection string is empty or invalid. Unable to write diagnostic events.
```

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Browser

Egde

**Comment by ccastrotrejo** [comment] 2023-12-22 18:07
Closing this one as a duplicate of https://github.com/Azure/logicapps/issues/943

**Closed** 2023-12-22 18:07 UTC
Labels: VSCode
