### ISSUE TITLE
Error when creating azureblob API-Connection using new Logic App designer view

### ISSUE THREAD

**Issue by SashWind** [Azure/LogicAppsUX#4479] opened 2024-03-28 15:58 UTC
### Describe the Bug with repro steps 

Created a new Logic App of type "Standard"

 Enabled system managed identity for Logic App

 Created a new workflow

 In workflow using designer view

 added trigger "When a blob is added or modified (properties only) (V2)"

 Tried to add API connection using *Logic Apps Managed Identity* as Authentication Type.

**Error:**

*Failed to create connection: {"error":{"code":"InvalidApiConnectionDynamicInvokeRequest","message":"The workflow reference is missing in the dynamic invocation request for api connection 'azureblob'. A reference to workflow with managed identity enabled is required for connections that are configured to be used with managed identity."}}*

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![LogicApp-ApiConnectionCreation-Error](<https://github.com/Azure/LogicAppsUX/assets/104893707/de269b38-57b3-4d4c-9246-84baa7aa6a67>)

### Browser 

Microsoft Edge 123.0.2420.65 (x64)

### Additional context 

To create an API Connection to azureblob worked yesterday, but it seems to be broken now. I tried to create a workflow from scratch starting with the trigger "When a blob is added or modified (properties only) (V2)". The Logic App is a Standard LA. It has a system managed identity enabled. Since today I always get an error when trying to create the mandatory API Connection using system managed identity. I tried to create an API Connection for azureblob in a "Consumption" Logic App. It didn't work either. Then I tried something else: I created another "Consumption" Logic App. In that app I changed the designer to legacy. When I tried to create the API Connection V1 it worked in the legacy designer. Only API Connection V2 cannot be created using the new designer.

**Comment by hartra344** [comment] 2024-03-28 16:00
Thank you for reporting this, just closing as a duplicate of #4478 . This is already being looked at

**Closed by hartra344** 2024-03-28 16:00 UTC
