### ISSUE TITLE
Fields unavailable in the subsequent actions

### ISSUE THREAD

**Issue by MisbahAfreen** [Azure/LogicAppsUX#2037] opened 2023-04-17 11:00 UTC
### Describe the Bug with repro steps

1. Open LogicApp designer
2. Click on 'Try Preview Designer'
3. Add a trigger 'When HTTP request is received'
4. Add the payload schema as well (Schema having )
5. Add Action 'HTTP'
6. Try to access the fields

Observation - All fields are not available to be used in next/subsequent steps.

However, in generally available designer, we can access all the fields defined in 'When HTTP request is received'.

I have attached screenshot for both the scenarios. 

### Workflow JSON

```json
NA
```

### Screenshots or Videos

In Preview Designer

![Fields_Unavailable_Error](https://user-images.githubusercontent.com/39396480/232465473-bddc62e1-f32e-4810-84c6-a39d48074423.PNG)

In Generally Available Designer

![Generally Available Designer_Fields](https://user-images.githubusercontent.com/39396480/232465571-6ffd9cda-37a5-4a12-9cad-cc36753e34fa.PNG)

### Browser

Chrome

**Comment by Eric-B-Wu** [comment] 2023-04-17 13:12
@MisbahAfreen Thanks for reporting this issue, looks like it was regression with some other changes we had made, will take a look and try to get this fixed by our next release

**Comment by Eric-B-Wu** [comment] 2023-04-17 20:34
@MisbahAfreen actually I'm not seeing this issue on my end, do you mind sharing your payload schema used in your request and I can try and repro it

**Comment by MisbahAfreen** [comment] 2023-04-26 09:45
Hi Eric,
Below is the payload I used to generate my schema:
**Payload:**
[
    {
        "name": "ABC",
        "siteId": "ABC-1",
        "address": null,
        "postalCode": null,
        "postOffice": null,
        "description": "",
        "relevant": null,
        "createdBy": null,
        "createdAt": null,
        "location": null,
        "status": "Active"
    },
    {
        "name": "DEF",
        "siteId": "DEF-1",
        "address": null,
        "postalCode": null,
        "postOffice": null,
        "description": "",
        "relevant": null,
        "createdBy": null,
        "createdAt": null,
        "location": null,
        "status": "Active"
    },
    {
        "name": "XYZ",
        "siteId": "XYZ-1",
        "address": null,
        "postalCode": null,
        "postOffice": null,
        "description": "",
        "relevant": null,
        "createdBy": null,
        "createdAt": null,
        "location": null,
        "status": "Active"
    }
]

**Payload Schema generated:**
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "siteId": {
                "type": "string"
            },
            "address": {},
            "postalCode": {},
            "postOffice": {},
            "description": {
                "type": "string"
            },
            "relevant": {},
            "createdBy": {},
            "createdAt": {},
            "location": {},
            "status": {
                "type": "string"
            }
        },
        "required": [
            "name",
            "siteId",
            "address",
            "postalCode",
            "postOffice",
            "description",
            "relevant",
            "createdBy",
            "createdAt",
            "location",
            "status"
        ]
    }
}

**Comment by Eric-B-Wu** [comment] 2023-04-28 18:46
@MisbahAfreen can we verify if this is still happening? I'm seeing all the expected outputs
![tpitems](https://user-images.githubusercontent.com/95886809/235228709-58625cd2-12fe-4d43-8a2a-072a49ea59f3.gif)
If this is still happening, feel free to reopen and we can have a deeper dive of why its happening for you

**Closed by Eric-B-Wu** 2023-04-28 18:46 UTC
Labels: bug
