### ISSUE TITLE
'Show Logic App Run Details' Button Doesn't Do Anything

### ISSUE THREAD

**Issue by edTomsRT** [Azure/LogicAppsUX#6000] opened 2024-10-31 11:50 UTC
### Describe the Bug with repro steps 

1. Create a logic app containing another logic app connector. 
2. Trigger a run. 
3. On run history, click on the sub logic app and click 'Show Logic App Run Details'. 
4. Nothing will happen. 

On the old designer this would allow you to view the run details of the sub logic app without having to go and find it separately (which can be quite hard to do with a lot of runs).

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-10-31 14:31
Closing as duplicate of https://github.com/Azure/LogicAppsUX/issues/5999
Please follow the above issue for progress on a fix

**Closed by rllyy97** 2024-10-31 14:31 UTC
