### ISSUE TITLE
Consumption: Unable to open desinger

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#3369] opened 2023-09-22 08:00 UTC
### Describe the Bug with repro steps

1. Create a logic app in consumption.
2. Open the designer

**Actual:** Designer should open 
**Expected:** Unable to open designer

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

** Old Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

https://github.com/Azure/LogicAppsUX/assets/113517384/d9f4ad67-1ed7-4c35-9119-08285d585286

### Browser

Edge

### Additional context

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7Cd24de414f5964989a4ca08dbbacbd79c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638309156917165480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oXFC8qpMAmFZIi7MayhNxMFh2gV65d%2FgJ2tlYUxZBIw%3D&reserved=0)
**Version:** 2.30920.1.1

AB#25240630

**Comment by rllyy97** [comment] 2023-09-22 14:22
This appears to be an issue with the loading state change that was made in Portal, I'll take a look at it and try to get it hotfixed

**Comment by rllyy97** [comment] 2023-09-22 15:46
@vgouth I tried loading both an existing app and creating a new app and was unable to reproduce this issue, could you provide any more info on your setup + how we could reproduce?
Also could you send me any console errors that are appearing, and/or a network trace of you trying to load the logic app?
My email is rileyevans@microsoft.com if you don't have it

**Comment by vgouth** [comment] 2023-09-22 16:10
@rllyy97 I sent you the mail with all the details along with HAR file.

**Comment by hartra344** [comment] 2023-09-22 16:38
I found the issue, fix will be in today

**Closed** 2023-09-22 16:53 UTC
Labels: Bug, Found By Testers, Needs More Info

**Comment by vgouth** [comment] 2023-10-12 12:34
Issue **not** repro in the latest request

**Environmental Details:**
**URL:** [https://aka.ms/emastagiLong-flowstip1](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging-flowstip1&data=05%7C01%7Cv-govubilish%40microsoft.com%7C812ecec939f943a0236b08dbcadb1346%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326814546516488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oaldsNa7sJEgX1lgFphSQLXmtCRZ%2FUm2tHxNj1Vff2I%3D&reserved=0)
**Version:** 2.31010.1.2

![image](https://github.com/Azure/LogicAppsUX/assets/113517384/30ae5d69-59b2-4bc5-a573-a358faff7bd7)
