### ISSUE TITLE
Automation: Tasks (preview) failed to turn on virtual machine.

### ISSUE THREAD

**Issue by joelrb** [Azure/LogicAppsUX#4872] opened 2024-05-21 05:08 UTC
### Describe the Bug with repro steps 

1. Go to Azure virtual machine. 
2. In Automation > Tasks (preview), Add a task and select Start Virtual Machine. 

The automated VM scheduled Turn-On failed because it's unauthorized. How do we authorize it when there's no step for that in the configuration of the Task?

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Screenshot 2024-05-21 130408](<https://github.com/Azure/LogicAppsUX/assets/225284/0c09ed84-caf6-42d6-ab71-f352cc256f5a>)

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment] 2024-06-14 18:11
duplicate of #4872

**Closed by hartra344** 2024-06-14 18:11 UTC
