### ISSUE TITLE
Text is unreadable with in dark mode

### ISSUE THREAD

**Issue by james-annages** [Azure/LogicAppsUX#1784] opened 2023-03-20 11:47 UTC
### Describe the Bug

when using the standard Logic app workflow designer the docked panel on the side has test that is unreadable when in bark mode. 
![image](https://user-images.githubusercontent.com/45330941/226329895-ac77ff31-ad46-4f46-9814-0512fee21e2b.png)

### Steps to Reproduce the Bug or Issue

1. Set azure portal in to dark mode
2. go to logic app Standard ->workflow
3. new work flow
4. add a any modal and the text in the config window will be unreadable 

### Expected behavior

As a user working in dark mode, test needs to auto invert to be readable

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#17605338

**Comment by Eric-B-Wu** [comment] 2023-03-20 14:06
@james-annages, thanks for reaching out about this issue. We have some work items currently in dark mode, so this should be resolved shortly. 

#1758 is the parent item we're using to track dark mode changes

**Comment by hartra344** [comment] 2023-03-20 18:05
Closing this issue since it's a duplicate of #1758. Thank you for taking the time to report, like Eric said, we're working to get this fixed quickly.

**Closed by hartra344** 2023-03-20 18:05 UTC

**Comment by hartra344** [comment] 2023-03-20 19:58
Actually the one we're currently tracking is #1749 . #1758 is another duplicate

**Comment by hartra344** [comment] 2023-03-21 19:59
tracked-by:#1749
