### ISSUE TITLE
Removing the double quotes from the setting value causes the time setting of the Recurrence trigger to be incorrect.

### ISSUE THREAD

**Issue by MitsuyoTakeda** [Azure/LogicAppsUX#6311] opened 2024-12-27 01:22 UTC
### Describe the Bug with repro steps 

1. Set the Recurrence trigger. 
2. In the designer view, set any time for "At These Hours." 
3. In the code view, remove the double quotes from the setting value of "At These Hours." 
4. When you reopen it in the designer view, the time setting for "At These Hours" appears to be unset. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
    "apiVersion": "2019-05-01",
    "id": "/subscriptions/243f01aa-1aff-4d2d-a4be-c9b79d7026fb/resourceGroups/Logic_Apps_Test/providers/Microsoft.Logic/workflows/Blog_Wiki",
    "name": "Blog_Wiki",
    "type": "microsoft.logic/workflows",
    "location": "japaneast",
    "properties": {
        "provisioningState": "Succeeded",
        "createdTime": "2024-10-22T01:34:41.112Z",
        "changedTime": "2024-12-27T01:05:36.869Z",
        "state": "Enabled",
        "version": "08584663453486226091",
        "accessEndpoint": "https://prod-11.japaneast.logic.azure.com:443/workflows/3b00c5c61c5d4094b1a4fcb01d3ed766",
        "definition": {
            "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
                "$connections": {
                    "defaultValue": {},
                    "type": "Object"
                }
            },
            "triggers": {
                "Recurrence": {
                    "recurrence": {
                        "interval": 1,
                        "frequency": "Day",
                        "timeZone": "Tokyo Standard Time",
                        "startTime": "2024-12-26T15:00:00Z",
                        "schedule": {
                            "hours": [
                                15,
                                "15"
                            ],
                            "minutes": [
                                0
                            ]
                        }
                    },
                    "evaluatedRecurrence": {
                        "interval": 1,
                        "frequency": "Day",
                        "timeZone": "Tokyo Standard Time",
                        "startTime": "2024-12-26T15:00:00Z",
                        "schedule": {
                            "hours": [
                                15,
                                "16"
                            ],
                            "minutes": [
                                0,
                                50
                            ]
                        }
                    },
                    "type": "Recurrence"
                }
            },
            "actions": {},
            "outputs": {}
        },
        "parameters": {
            "$connections": {
                "value": {}
            }
        },
        "endpointsConfiguration": {
            "workflow": {
                "outgoingIpAddresses": [
                    {
                        "address": "13.71.158.3"
                    },
                    {
                        "address": "13.73.4.207"
                    },
                    {
                        "address": "13.71.158.120"
                    },
                    {
                        "address": "13.78.18.168"
                    },
                    {
                        "address": "13.78.35.229"
                    },
                    {
                        "address": "13.78.42.223"
                    },
                    {
                        "address": "13.78.21.155"
                    },
                    {
                        "address": "13.78.20.232"
                    },
                    {
                        "address": "20.191.172.255"
                    },
                    {
                        "address": "20.46.187.174"
                    },
                    {
                        "address": "20.194.206.98"
                    },
                    {
                        "address": "20.194.205.189"
                    },
                    {
                        "address": "20.18.198.224"
                    },
                    {
                        "address": "20.18.197.177"
                    },
                    {
                        "address": "20.18.198.141"
                    },
                    {
                        "address": "20.18.238.83"
                    },
                    {
                        "address": "4.189.14.67"
                    },
                    {
                        "address": "4.189.8.211"
                    },
                    {
                        "address": "4.189.9.135"
                    },
                    {
                        "address": "4.189.8.208"
                    }
                ],
                "accessEndpointIpAddresses": [
                    {
                        "address": "13.71.146.140"
                    },
                    {
                        "address": "13.78.84.187"
                    },
                    {
                        "address": "13.78.62.130"
                    },
                    {
                        "address": "13.78.43.164"
                    },
                    {
                        "address": "20.191.174.52"
                    },
                    {
                        "address": "20.194.207.50"
                    },
                    {
                        "address": "20.18.198.232"
                    },
                    {
                        "address": "20.18.197.179"
                    },
                    {
                        "address": "20.18.198.148"
                    },
                    {
                        "address": "20.18.238.86"
                    },
                    {
                        "address": "4.189.8.207"
                    },
                    {
                        "address": "4.189.9.80"
                    },
                    {
                        "address": "4.189.10.88"
                    },
                    {
                        "address": "4.189.8.209"
                    }
                ]
            },
            "connector": {
                "outgoingIpAddresses": [
                    {
                        "address": "13.73.21.230"
                    },
                    {
                        "address": "13.71.153.19"
                    },
                    {
                        "address": "13.78.108.0/28"
                    },
                    {
                        "address": "40.79.189.64/27"
                    },
                    {
                        "address": "20.89.11.48/28"
                    },
                    {
                        "address": "20.89.11.64/27"
                    },
                    {
                        "address": "20.89.163.17"
                    },
                    {
                        "address": "20.89.163.9"
                    }
                ]
            }
        }
    }
}
```

### Screenshots or Videos

■ Reproduction of the steps to reproduce the issue

 Set the Recurrence trigger, and in the designer view, set any time for "At These Hours.

![Image](<https://github.com/user-attachments/assets/7dc5ea5f-c640-48da-bf75-9e75e68ddfaa>)

![Image](<https://github.com/user-attachments/assets/6233faf3-d4b5-4da5-8066-1409d8f19920>)

In the code view, remove the double quotes from the setting value of "At These Hours.

![Image](<https://github.com/user-attachments/assets/85534bcc-67ad-40e1-b211-2702e4a26094>)

When you reopen it in the designer view, the time setting for "At These Hours" appears to be unset.

![Image](<https://github.com/user-attachments/assets/8a35c30e-453d-476b-a4ca-f82b2904ce20>)

In this state, if you set the time again from the designer view, the same time will be set, resulting in a validation error.

![Image](<https://github.com/user-attachments/assets/43b1362d-6074-4bf8-abf2-8cb3a3b790a6>)

![Image](<https://github.com/user-attachments/assets/4d5ee07d-a669-479e-b0ff-3bbf56eefde8>)

### Browser

Microsoft Edge

### Additional context

In the old UI, the time setting was read correctly even without double quotes, so this issue did not occur.

![Image](<https://github.com/user-attachments/assets/acbadd5f-092b-4488-b21e-5be49245bff5>)

![Image](<https://github.com/user-attachments/assets/5a06654e-c40a-4483-bf8a-deb94875c2a1>)

**Comment by Eric-B-Wu** [comment] 2024-12-27 19:01
removing as duplicate of https://github.com/Azure/LogicAppsUX/issues/6312

**Closed by Eric-B-Wu** 2024-12-27 19:01 UTC
