### ISSUE TITLE
LA standard "Invoke a workflow" action designer validation error with ["string", "null"] type input parameter

### ISSUE THREAD

**Issue by huidongl** [Azure/LogicAppsUX#3274] opened 2023-09-07 02:38 UTC
### Describe the Bug with repro steps

Logic App standard workflow1 use "invoke workflow in this workflow app" to invoke workflow2 with HTTP trigger. And from **Aug 14th**, the designer view of this action started to show the validation error "_XXX is no longer present in the operation schema. It should be removed before the workflow is re-saved_." This error will be shown if the parameter is defined as nullable, "type": **[ "string", "null"]**, if the type does not accept null, and string only, "type": "string", it will no throw error. 

The code view of this action can be saved without error, and Logic App is able to execute successfully. But the designer view is not able to be saved. There was no issues until Aug 14th, customer found they are not able to save new changes in the workflow. 

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
*********************************************************
Invoke_a_workflow_in_this_workflow_app workflow.json
*********************************************************

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Complete_the_message_in_a_queue_x": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "servicebus"
                        }
                    },
                    "method": "delete",
                    "path": "/@{encodeURIComponent(encodeURIComponent('matt'))}/messages/complete",
                    "queries": {
                        "lockToken": "@triggerBody()?['LockToken']",
                        "queueType": "Main",
                        "sessionId": ""
                    }
                },
                "runAfter": {
                    "Compose": [
                        "SUCCEEDED"
                    ]
                },
                "type": "ApiConnection"
            },
            "Compose": {
                "inputs": "@body('Invoke_a_workflow_in_this_workflow_app')",
                "runAfter": {
                    "Invoke_a_workflow_in_this_workflow_app": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Compose"
            },
            "Invoke_a_workflow_in_this_workflow_app": {
                "inputs": {
                    "body": {
                        "addressLine1": "@body('Parse_JSON')['address']['addressLine1']",
                        "addressLine2": "@body('Parse_JSON')['address']['addressLine2']",
                        "addressLine3": "@body('Parse_JSON')['address']['addressLine3']",
                        "addressValidated": "@body('Parse_JSON')['address']['addressValidated']",
                        "addressValidatedDate": "@body('Parse_JSON')['address']['addressValidatedDate']",
                        "country": "@body('Parse_JSON')['address']['country']",
                        "fromDate": "@utcNow()",
                        "postcode": "@body('Parse_JSON')['address']['postcode']",
                        "state": "@body('Parse_JSON')['address']['state']",
                        "suburb": "@body('Parse_JSON')['address']['suburb']"
                    },
                    "host": {
                        "workflow": {
                            "id": "mattHttp"
                        }
                    }
                },
                "runAfter": {
                    "Parse_JSON": [
                        "SUCCEEDED"
                    ]
                },
                "type": "Workflow"
            },
            "Parse_JSON": {
                "inputs": {
                    "content": "@base64ToString(triggerBody()?['ContentData'])",
                    "schema": {
                        "$defs": {
                            "address": {
                                "properties": {
                                    "addressLine1": {
                                        "type": "string"
                                    },
                                    "addressLine2": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "addressLine3": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "addressValidated": {
                                        "type": "boolean"
                                    },
                                    "addressValidatedDate": {
                                        "format": "date-time",
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "country": {
                                        "type": "string"
                                    },
                                    "postcode": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "state": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "suburb": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    }
                                },
                                "required": [
                                    "addressLine1",
                                    "country"
                                ],
                                "type": [
                                    "object",
                                    "null"
                                ]
                            }
                        },
                        "$schema": "https://json-schema.org/draft/2020-12/schema",
                        "description": "",
                        "properties": {
                            "address": {
                                "$ref": "#/$defs/address"
                            },
                            "mattInteger": {
                                "type": "integer"
                            },
                            "mattValue": {}
                        },
                        "required": [
                            "address"
                        ],
                        "title": "Matt",
                        "type": "object"
                    }
                },
                "runAfter": {},
                "type": "ParseJson"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_message_is_received_in_a_queue_(peek-lock)": {
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "servicebus"
                        }
                    },
                    "method": "get",
                    "path": "/@{encodeURIComponent(encodeURIComponent('matt'))}/messages/head/peek",
                    "queries": {
                        "queueType": "Main",
                        "sessionId": "None"
                    }
                },
                "recurrence": {
                    "frequency": "Minute",
                    "interval": 3
                },
                "type": "ApiConnection"
            }
        }
    },
    "kind": "Stateful"
}



*********************************************************
HTTP trigger workflow.json
*********************************************************

{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Response": {
                "inputs": {
                    "body": "@triggerBody()",
                    "statusCode": 200
                },
                "kind": "Http",
                "runAfter": {},
                "type": "Response"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "inputs": {
                    "method": "POST",
                    "schema": {
                        "properties": {
                            "addressLine1": {
                                "type": "string"
                            },
                            "addressLine2": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "addressLine3": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "addressValidated": {
                                "type": [
                                    "boolean"
                                ]
                            },
                            "addressValidatedDate": {
                                "format": "date-time",
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "country": {
                                "type": "string"
                            },
                            "fromDate": {
                                "type": "string"
                            },
                            "postcode": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "state": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "suburb": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            }
                        },
                        "required": [
                            "addressLine1",
                            "addressLine2",
                            "addressLine3",
                            "suburb",
                            "state",
                            "postcode",
                            "country",
                            "fromDate"
                        ],
                        "type": "object"
                    }
                },
                "kind": "Http",
                "operationOptions": "EnableSchemaValidation",
                "type": "Request"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/92560328/35ca73fa-eab4-42c4-9193-8b55ca99dc1a)

### Browser

Chrome, edge

AB#25092433

**Comment by Eric-B-Wu** [comment] 2023-09-07 16:02
Hi @huidongl, this seems like the error is showing now because only recently did we change designer to validate all parameters on save: https://github.com/Azure/LogicAppsUX/pull/3040. However, I believe this error was always there - though I think the issue is that we currently don't support array types ["string", "null"] for our schema types. Once I moved them to strings, I no longer was getting the error. Let me confirm with the team if this was intended, or if this was an overlooked feature

**Comment by huidongl** [comment] 2023-09-08 01:17
Hi @Eric-B-Wu customer mentioned they have been using the array type  ["string", "null"]  schema for long time and the designer had no issues until Aug 14th. The code view of is actually included in the body {}, and it will run successfully with null input, that indicates the array type  ["string", "null"] schema is supported. 


I have also asked customer to try with the  {"type": "string", "nullable": true} schema in HTTP trigger, the designer validation will pass, however, when executing the invoke action with a null value, the invoke workflow action will fail with following error:
`{
  "error": {
    "code": "TriggerInputSchemaMismatch",
    "message": "The input body for trigger 'When_a_HTTP_request_is_received' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'."
  }
}`

**Comment by huidongl** [comment] 2023-09-14 06:28
Hi @Eric-B-Wu , our customer is using the code view as a workaround but would like to get an ETA for the fix of the designer. May I know if there is any information that I can share with the customer regarding the timeline of this issue? Thanks!

**Comment by preetriti1** [comment] 2023-09-27 02:06
This should be fixed in 2 weeks in our next release.

**Closed** 2023-09-27 16:19 UTC
