### ISSUE TITLE
Can't save workflow changes because of Auth error?

### ISSUE THREAD

**Issue by dave-read** [Azure/LogicAppsUX#3766] opened 2023-11-29 07:50 UTC
### Describe the Bug with repro steps

Working in the designer and tried to save a substantial amount of changes.  Every attempt to save fails with error: 

Workflow validation failed for the workflow 'send-receive-scale-messages'. {"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '11/29/2023 7:45:06 AM' is earlier than current UTC time '11/29/2023 7:47:04 AM'."}}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

### Additional context

This doesn't look like a problem with the Workflow.  It seems my session in the Portal is broken with no way out.

AB#25990389

**Comment by rllyy97** [comment] 2023-11-29 16:32
Hi @dave-read thanks for the report, this is a duplicate of https://github.com/Azure/LogicAppsUX/issues/3766, I'm going to be working on this over the next few days and will give any updates over on that issue.

**Closed by rllyy97** 2023-11-29 16:32 UTC
Labels: triage

**Comment by preetriti1** [comment] 2023-11-29 20:56
Seems to be an issue with portal framework, i have posted a question in stackoverflow for their team to answer - https://stackoverflow.microsoft.com/questions/379759

**Comment by preetriti1** [comment] 2023-12-05 18:33
@dave-read - The issue is fixed by Portal team and till it makes it to production please use this link - https://rc.portal.azure.com/
