### ISSUE TITLE
i have problem in logic app : in design when add action SQL Server table through a Logic App action, and the same parameters are being  at all table

### ISSUE THREAD

**Issue by mahmoudalsamman20** [Azure/LogicAppsUX#4667] opened 2024-04-22 08:16 UTC
### Describe the Bug with repro steps

 in design when add action SQL Server table through a Logic App action, and the same parameters are being  at all table

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

chrome

**Comment by hartra344** [comment] 2024-04-22 14:07
I'm sorry, I don't really understand what you're trying to say here. Can you post a screenshot/video showing what you mean?

**Comment by mahmoudalsamman20** [comment] 2024-04-24 10:56
When using the Sql server, it always sets the same parameter; I think it doesn't reload the table I selected.

**Comment by mahmoudalsamman20** [comment] 2024-04-24 10:57
> I'm sorry, I don't really understand what you're trying to say here. Can you post a screenshot/video showing what you mean?



> I'm sorry, I don't really understand what you're trying to say here. Can you post a screenshot/video showing what you mean?

When using the Sql server, it always sets the same parameter; I think it doesn't reload the table I selected.
![Screenshot 2024-04-24 135019](https://github.com/Azure/LogicAppsUX/assets/109543626/3a22eb03-5f97-4149-a89b-c94c552e5492)
![Screenshot 2024-04-24 135043](https://github.com/Azure/LogicAppsUX/assets/109543626/ab4b098d-9b6d-4839-aeaf-985c2c6eec9a)
![Screenshot 2024-04-24 135105](https://github.com/Azure/LogicAppsUX/assets/109543626/0b019b0d-9bd3-4df1-9b6a-59bf3b4919c0)

**Comment by hartra344** [comment] 2024-04-24 14:53
@eric-b-wu can you take a look?

**Comment by Eric-B-Wu** [comment] 2024-04-24 23:20
Would you be able to see if the issue is fixed in:
http://portal.azure.com/?feature.canmodifystamps=true&Microsoft_Azure_EMA=hotfix#home
We're currently hotfixing a different issue, but it may be linked with this one

**Closed** 2024-04-25 15:26 UTC
