### ISSUE TITLE
Creating New Data Map, Nothing Appears after Naming

### ISSUE THREAD

**Issue by WilliamDShiell** [Azure/LogicAppsUX#4562] opened 2024-04-05 17:22 UTC
### Describe the Bug with repro steps 

Environment Information

 Workstation: Windows 11 Version 23H2 Build 22631.3296

 VS Code Version 1.88.0

 Using Logic Apps Standard Extension v3.0.3

Reproduce Steps:

 Step 1. Select Button "Create new data map"

 Step 2. Pop Up will appear asking for Data Map Name, enter name

Nothing else happens, no ui loads.

 Side note I am seeing an info popup saying "Validating Runtime Dependency: Function Runtime", I dont think this is related but adding as additional info incase its needed.

### Screenshots or Videos 

*No response*

### Version 

v3.0.2

### Additional context 

*No response*

**Comment by DanielleCogs** [comment] 2024-04-08 17:39
Hi @WilliamDShiell I'm looking into your issue and so far I can't reproduce it. Could you attach a screenshot of what you see after you type in the name? Another thing that would be helpful is the text from "Output" in VSCode, and select 'Azure Logic Apps' from the dropdown, and you should see some logs there, or maybe an error message.

**Comment by DanielleCogs** [comment] 2024-04-08 17:43
One thing to try- it is possible the extension is hanging somewhere when installing the Functions Runtime. As a possible fix, could you install that dependency separately? Please let me know if that helps, and we can work on making that experience better.

**Comment by WilliamDShiell** [comment] 2024-04-08 19:21
Can confirm functions extension is already installed. 

New Error Message Appearing today, see screenshot. Any idea of the resolution steps here?
![VSCode Issue](https://github.com/Azure/LogicAppsUX/assets/22339280/935fb8fb-f4b3-4deb-a8eb-70cd96e45bbe)

**Comment by ccastrotrejo** [comment] 2024-04-09 22:04
Hey @WilliamDShiell, which version of the Logic Apps Standard extension are you using? I can see two differences in the initial context of the issue. 

The latest error that you are experiencing is due to the extension not being activated. Usually, the commands aren't exposed until the extension gets fully activated, and an issue during the activation will make all of them fail. Do you see any other error previous this one?

**Comment by WilliamDShiell** [comment] 2024-04-10 03:03
Hey @ccastrotrejo running version 3.0.3. Waited 20 minutes for extension to load and looks like we are back to the original behavior. Attaching screenshot of the terminal output set to Output the Azure Logic Apps Standard.

Same behavior as before:
Step1. Select Create new Data Map
Step2. Plug in value for map name and hit enter.

No changes to terminal output or anything noticable in VS Code. Is there anywhere in terminal other than output I should be looking for logs?
![Screenshot 2024-04-09 213926](https://github.com/Azure/LogicAppsUX/assets/22339280/1b050871-8774-4190-8990-bdf9f9c20c17)

**Comment by ccastrotrejo** [comment] 2024-04-10 17:25
Hi @WilliamDShiell thanks for sharing your screenshot. I am still looking at what might be wrong with the installation of dependencies on your end. In the meantime could you please check if the following extension setting are configured as follow? 
<img width="932" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/5daa0542-e5b6-4569-9e62-c5e4dae017b9">
<img width="942" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/df53607a-17fe-49a0-9bf3-f10d52b4535f">
<img width="904" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/d213c4e1-3454-40dd-86e2-a9e226aa9f03">
<img width="950" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/102700317/5a725247-594a-461a-8e2c-ba51da20c3a6">

**Comment by WilliamDShiell** [comment] 2024-04-15 15:50
Auto Runtime Dependencies Path: Correct
Auto Runtime Dependencies Validation and Installation: Correct
Auto Start Azurite: Correct
Auto Start Design Time: Correct
Azurite Location Settings: Correct

Dotnet Binary Path: Correct
Func Core Tools Binary Path: Correct
Node JS Binary Path: Correct

**Comment by ccastrotrejo** [comment] 2024-04-19 18:27
Hi @WilliamDShiell, sorry for the delayed response. I don't see any other way that the extension initialization its failing besides the error from the screenshot above about the `path` not being sent correctly, I will keep investigation where this is happening. Please if this is still happening and if you see any other error, please let me know.

Also you can take a look at the console tab from the developer tools. To open it you can do the following

1. `Ctrl`+`Shift`+`P` -> will open the command palette
2. Type `Toggle developers tool`
3. Click in `Console` tab

**Comment by WilliamDShiell** [comment] 2024-04-19 18:37
Hey @ccastrotrejo,

Adding a few new error messages. Hoping this may help point to the issue:

Receive this message starting up VS Code when connected to proxies:
![Request Timeout](https://github.com/Azure/LogicAppsUX/assets/22339280/99405dec-ae66-457f-b901-d3bda6623505)


When disconnected to proxies receive this error message today:
![image](https://github.com/Azure/LogicAppsUX/assets/22339280/a9827f87-cba4-4057-b020-21e3133977d7)


Would it be worth it to do a complete uninstall of VS Code + Extensions and attempt again? Could either of these error messages help point to the root issue?

**Comment by WilliamDShiell** [comment] 2024-04-19 18:47
Adding Additional Screenshots, selecting **Create new data map** brings up the type name prompt but does nothing else, no new events appear in the console

Selecting **Load existing data map** brings up event in console "The "path" argument must be of type string, received undefined"
![image](https://github.com/Azure/LogicAppsUX/assets/22339280/f52111fd-3299-4b22-9437-a867a54b1ca0)

**Comment by ccastrotrejo** [comment] 2024-04-19 19:34
Ok, this makes more sense. Yeah I think it would not make anything worse uninstalling the extension, remove the dependencies folder and install it again. The request timeout error is showing up as it is taking longer to check the dependencies and download them, if you want to increase it in extensions settings that's also good.

So neither of the two commands show something in terms of the UI in vscode?

**Comment by WilliamDShiell** [comment] 2024-04-19 19:58
Other than the Create New opening up the box to name the map, neither of the buttons work.

**Comment by WilliamDShiell** [comment] 2024-04-19 20:20
Finished fresh install, still seeing the same issues. Is there anywhere else we can check for logs?

**Comment by ccastrotrejo** [comment] 2024-05-07 03:03
Hi @WilliamDShiell I heard from our Customer Support team, the issue got resolved. I will close the issue but wanted to write down the state of the issues found on this thread.

1. `"The "path" argument must be of type string, received undefined"` -> Reason of the issue is because a logic app project must be open in vscode in order to create and load the data map file. I will work on implementing an experience in which the user can open/create a project from it and update the official documentation.
2. `'azureLogicAppsStandard.dataMap.createNewDataMap' not found` -> Root cause of the issue is that the extension isn't getting activated properly, therefore all the commands get disable and unable to trigger. I still haven't found what is causing the extension to not get activated, but I will work on trying to repro it.

**Closed by ccastrotrejo** 2024-05-07 03:03 UTC
Labels: VSCode, Data Mapper
