### ISSUE TITLE
Logic App Failed to Save

### ISSUE THREAD

**Issue by ZLT-ops** [Azure/LogicAppsUX#2074] opened 2023-04-19 23:39 UTC
### Describe the Bug with repro steps

The bug happened on the new UX for the Logic App.
The steps that i did:

1. Edited the Logic App in the Logic App Designer
2. Hit Save
3. On a different window resubmitted the run, The Logic App didn't change
4. Tried again to hit Save, no change
5. Tried to exit to the Overview section, was prompt that the changes where not saved

### Browser

Google Chrome Version 112.0.5615.121 (Official Build) (x86_64)

**Comment by preetriti1** [comment] 2023-05-05 23:04
@ZLT-ops - We have recently fixed the issue where after saving your changes when you exit to any other blade it wont show the prompt so it should be available by next week end. also Save button will be disabled if there are no pending changes.

For the other issues reported where you resubmit a run from a different window, can you elaborate on this repro?
1. Was your run not picking up latest made definition changes in the run?
2. What did not change in the Logic App?

**Comment by rllyy97** [comment] 2023-05-19 15:38
@ZLT-ops - From the information you've provided I'm guessing that this is a duplicate of our general consumption save issues you can find here: https://github.com/Azure/LogicAppsUX/issues/2388
We are aiming to have this fixed in our upcoming release (June 2nd), and if you're still experiencing issues afterwards please feel free to leave a comment on our known issue!

**Closed by rllyy97** 2023-05-19 15:38 UTC
Labels: Needs More Info, Portal
