### ISSUE TITLE
Typing issue in my logic app - Boolean

### ISSUE THREAD

**Issue by j-daggs** [Azure/LogicAppsUX#4644] opened 2024-04-18 19:39 UTC
### Describe the Bug with repro steps

In an action "initialize variable 1" in my logic app I initialize a boolean variable "conitnue" as "true". Later there is a step "set variable 2" where I am trying to have it set to false, but I am getting an error "please enter a valid array". This error makes no sense since it is a boolean, false should be acceptable. When I try to save it will tell me the same thing for my Initialize variable 1 action, even though the type is boolean.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "interval": 3,
          "frequency": "Month"
        }
      }
    },
    "actions": {
      "Stitch_V3_API_ApparelMagic_Authentication": {
        "type": "Workflow",
        "inputs": {
          "host": {
            "workflow": {
              "id": "/subscriptions/4ba4d602-8c23-4b65-9c62-ca1bc3197244/resourceGroups/Stitch_V3/providers/Microsoft.Logic/workflows/Stitch_V3_API_ApparelMagic_Authentication"
            },
            "triggerName": "manual"
          }
        },
        "runAfter": {}
      },
      "Until": {
        "type": "Until",
        "expression": "@equals(variables('continue'),'false')",
        "limit": {
          "count": 100,
          "timeout": "PT1H"
        },
        "actions": {
          "GetProducts": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "name": "@parameters('$connections')['V3-API-ApparelMagic-20221215']['connectionId']"
                }
              },
              "method": "get",
              "path": "/products",
              "queries": {
                "time": "@body('Stitch_V3_API_ApparelMagic_Authentication')?['time']",
                "token": "@{body('Stitch_V3_API_ApparelMagic_Authentication')?['token']}",
                "pagination[page_size]": 1000,
                "pagination[last_id]": "@variables('last_id')",
                "parameters[0][field]": "is_emblem",
                "parameters[0][value]": "1",
                "parameters[0][operator]": "="
              }
            }
          },
          "Compose": {
            "type": "Compose",
            "inputs": "@union(body('GetProducts')?['response'],variables('EmblemArray'))",
            "runAfter": {
              "GetProducts": [
                "Succeeded"
              ]
            }
          },
          "Set_variable": {
            "type": "SetVariable",
            "inputs": {
              "name": "EmblemArray",
              "value": "@outputs('Compose')"
            },
            "runAfter": {
              "Compose": [
                "Succeeded"
              ]
            }
          },
          "Condition": {
            "type": "If",
            "expression": {
              "and": [
                {
                  "not": {
                    "equals": [
                      "@body('GetProducts')?['meta']?['pagination']?['last_id']",
                      "@null"
                    ]
                  }
                }
              ]
            },
            "actions": {
              "Set_variable_1": {
                "type": "SetVariable",
                "inputs": {
                  "name": "last_id",
                  "value": "@int(body('GetProducts')?['meta']?['pagination']?['last_id'])"
                }
              }
            },
            "else": {
              "actions": {
                "Set_variable_2": {
                  "type": "SetVariable",
                  "inputs": {
                    "name": "continue",
                    "value": false
                  }
                }
              }
            },
            "runAfter": {
              "Set_variable": [
                "Succeeded"
              ]
            }
          }
        },
        "runAfter": {
          "Initialize_variable_2": [
            "Succeeded"
          ]
        }
      },
      "Initialize_variable": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "last_id",
              "type": "integer",
              "value": 0
            }
          ]
        },
        "runAfter": {
          "Stitch_V3_API_ApparelMagic_Authentication": [
            "Succeeded"
          ]
        }
      },
      "Initialize_variable_2": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "EmblemArray",
              "type": "array"
            }
          ]
        },
        "runAfter": {
          "Initialize_variable_1": [
            "Succeeded"
          ]
        }
      },
      "For_each": {
        "type": "Foreach",
        "foreach": "@variables('EmblemArray')",
        "actions": {
          "HTTP": {
            "type": "Http",
            "inputs": {
              "uri": "https://stitchgolf.app.apparelmagic.com/api/json/products/@{items('For_each')?['product_id']}",
              "method": "PUT",
              "queries": {
                "token": "@{body('Stitch_V3_API_ApparelMagic_Authentication')?['token']}",
                "time": "@{body('Stitch_V3_API_ApparelMagic_Authentication')?['time']}"
              },
              "body": {
                "time": "@{body('Stitch_V3_API_ApparelMagic_Authentication')?['time']}",
                "token": "@{body('Stitch_V3_API_ApparelMagic_Authentication')?['token']}",
                "is_returnble": "1"
              }
            }
          }
        },
        "runAfter": {
          "Until": [
            "Succeeded"
          ]
        }
      },
      "Initialize_variable_1": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "continue",
              "type": "boolean",
              "value": true
            }
          ]
        },
        "runAfter": {
          "Initialize_variable": [
            "Succeeded"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "V3-API-ApparelMagic-20221215": {
          "id": "/subscriptions/4ba4d602-8c23-4b65-9c62-ca1bc3197244/resourceGroups/Stitch_V3/providers/Microsoft.Web/customApis/V3-API-ApparelMagic-20221215",
          "connectionId": "/subscriptions/4ba4d602-8c23-4b65-9c62-ca1bc3197244/resourceGroups/Stitch_V3/providers/Microsoft.Web/connections/V3-API-ApparelMagic-20221215",
          "connectionName": "V3-API-ApparelMagic-20221215"
        }
      }
    }
  }
}

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/122485585/fdf87012-e559-4a12-9213-190d04240553)

![image](https://github.com/Azure/LogicAppsUX/assets/122485585/0f98a3c3-4154-45e6-a46f-c6a998d2f3d6)

### Browser

Chrome

**Comment by j-daggs** [comment] 2024-04-19 12:14
By the way, switching to legacy designer, making the correct changes, and saving fixed the issue. So, I'm guessing it is something specific with the new designer causing this bug.

**Comment by Eric-B-Wu** [comment] 2024-04-19 14:42
@j-daggs thanks for reporting this issue, we're gonna look to prioritize this and get a hotfix for today. Will update on this once we have a root cause and a fix incoming

**Comment by Eric-B-Wu** [comment] 2024-04-19 15:49
We have a fix for this, which we'll be hotfixing over the next 3-4 hours. Apologies for the inconvenience

**Closed** 2024-04-19 19:53 UTC
Labels: Regression
