### ISSUE TITLE
Cannot scroll to see runs on my laptop

### ISSUE THREAD

**Issue by shahparth-lab** [Azure/LogicAppsUX#5798] opened 2024-10-02 18:39 UTC
### Describe the Bug with repro steps 

1. Use a surface laptop 3 
2. create a consumption logic app 
3. trigger a run 
4. Unable to see the run in Overvierw tab 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment] 2024-10-03 18:04
Hi @shahparth-lab thanks for raising this issue. I will send you a DM on Teams to ask you about it to have a better understandment on why this is happening.

**Comment by ccastrotrejo** [comment] 2024-10-04 16:50
Ok, I will close this issue as there isn't a tendency of users complainig about this, and the expected behavior when this happen is to minimize the `Essentials` tab so users can properly see the run history list

If I see any other issue like this in the future we can re visit it. 

Also, I removed image from the issue since it has some subscription information.

**Closed by ccastrotrejo** 2024-10-04 16:50 UTC
Labels: Portal
