### ISSUE TITLE
Switching between the old and new UI causes line breaks of the text incorrect

### ISSUE THREAD

**Issue by metakahash1** [Azure/LogicAppsUX#5463] opened 2024-08-22 05:03 UTC
### Describe the Bug with repro steps 

1. Edit and save the contents of the Teams connector in the old UI.

![image](<https://github.com/user-attachments/assets/6a112ce1-9d27-490e-b35f-3d7fa1443b6d>)

 
2. Switch to the new UI ([Generally Available Designer] button)

 
3. Edit and save contents of Teams connector in new UI. 

**\-> Line breaks on the UI appear to be missing.** 

![image](<https://github.com/user-attachments/assets/dc752ef4-3310-4165-a15c-b7d33ccb0d16>)

 

**\-> `"&lt;br&gt;\n"`appears to change to `"&lt;span&gt;&lt;/span&gt;"` in the code view as well.**

 Light side is the code view of old UI and right side is the code view of new UI.

![image](<https://github.com/user-attachments/assets/b8f298b3-2e5c-4692-a85e-422f3d8b9a9d>)

4. Revert to the old UI again.

 Line breaks appear to be broken.

![image](<https://github.com/user-attachments/assets/9711bba8-6140-4a5c-9af8-f31a0b009f4a>) 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
Please check "Describe the Bug with repro steps".
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

This issue also occurs with the [Office 365 Outlook] connector.

**Comment by Eric-B-Wu** [comment] 2024-08-22 16:51
there's been a couple html editor prs that PA has put out, I had asked them to verify that these simple line break issues wouldn't cause regressions, @ccastrotrejo, if you can verify if this is a regression from one of these?
https://github.com/Azure/LogicAppsUX/pull/5392
https://github.com/Azure/LogicAppsUX/pull/5318

**Comment by ccastrotrejo** [comment] 2024-08-22 16:55
Sure thing, I can take a look at these. Thanks for pointing these out!

**Comment by ccastrotrejo** [comment] 2024-08-22 19:00
Ok, I spend sometime looking at these and I can confirm that this issue is fixed in this PR https://github.com/Azure/LogicAppsUX/pull/5392.

**Comment by ccastrotrejo** [comment] 2024-08-22 19:13
I will close it since this is fixed in the above PR and triage with the team to hotfix it

**Closed by ccastrotrejo** 2024-08-22 19:13 UTC

**Comment by ccastrotrejo** [comment] 2024-08-22 20:24
@metakahash1 I figured out this issue is happening just when moving from old to new UI. 
If you start/add the action from scratch in the new UI this will not happen and text will be displayed as expected. 

Since this works fine in the new designer and old designer is going away soon, this will not hotfixed but will likely be fixed in the next release cycle

**Comment by metakahash1** [comment] 2024-08-23 00:13
Hi @ccastrotrejo , thank you for your investigation! This behavior also occurs when operating only with the new UI. If we set the text as follows on the new UI, click elsewhere in the designer, and then reopen this action again, the line breaks will be broken.

Before
![image](https://github.com/user-attachments/assets/b1951209-5197-4053-b206-972e76faacc5)

After
![image](https://github.com/user-attachments/assets/18b8a2c5-b9ff-4a31-94f8-2788d9affdcf)

**Comment by ccastrotrejo** [comment] 2024-08-23 00:31
Hi @metakahash1 ok ok. 
- Do you have any text you can share with me so I can give it a try?
- Did you copied and pasted the text from the old UI to the new one?

I tried by writing the text/message content from scratch in the new UI and doesn't happen.

If you copied and pasted the text what can be happening is that not only the text is getting copied, the tags and the general structure is getting copied as well

**Comment by metakahash1** [comment] 2024-08-23 00:40
Hi @ccastrotrejo , thank you for your quick response!
> Do you have any text you can share with me so I can give it a try?
Yes, this is the text I could repro. (It is a random string of characters with absolutely no meaning in Japanese.)
--------
おれは当時いよいよある意味目に対して事のためでやっつけないで。

何だか場合の仕事隊はいよいよそうした話なでだけを折って下さいだにも評価なるでまして、そうには知っなけれたたませ。

中学を亡びで事ももっとも結果を同じくずだます。

ちゃんと三宅さんを安心慣例もう少し拡張が殖やしる力その金そこか支配にというご観察なけれですんなけれが、その結果は何か考人格を引き返して、ネルソンさんの事をばらばらのそれに依然としてご相違と充たすて私傚を不発展をすまようにとうとうご意味から喰わたたが、ほぼついに徹底が充たすでて来るたものに出でなけれ。
--------

> Did you copied and pasted the text from the old UI to the new one?
No, I pasted this as plain text from VS code.

**Comment by ccastrotrejo** [comment] 2024-08-23 00:45
ok that makes sense. I was able to repro it with any other text that I copied and pasted from VS code

**Comment by ccastrotrejo** [comment] 2024-08-23 18:15
@metakahash1 as a workaround for now please use the input text in the new UI to write your text message from scratch. A new fix will be deployed in the timespan of the next 2 weeks.

**Comment by metakahash1** [comment] 2024-08-26 07:15
Hi @ccastrotrejo , thank you for your reply! I will wait for the fix.

**Comment by metakahash1** [comment] 2024-08-30 07:18
Hi @ccastrotrejo , could you let me know here when the rollout of the fix is complete? Or if you have a specific schedule in mind, could you let me know?

**Comment by ccastrotrejo** [comment] 2024-08-30 16:43
Hi @metakahash1 we will start rolling the new deployment on next Tuesday

**Comment by metakahash1** [comment] 2024-09-02 06:16
Hi @ccastrotrejo , oh, tomorrow (9/3)? Thank you for dealing with it so quickly! I will check the behavior the day after tomorrow.

**Comment by metakahash1** [comment] 2024-09-05 02:43
Hi @ccastrotrejo , I checked the behavior but the fix does not appear to have been deployed yet. Could you please confirm this?
set the text as follows
![image](https://github.com/user-attachments/assets/ac2efcdb-816a-4af9-b2fb-427e5828151b)

click elsewhere in the designer, and then reopen this action again, the line breaks will be broken.
![image](https://github.com/user-attachments/assets/c2faa1c4-86e8-44b8-9e6f-1df2c1d2732a)

**Comment by ccastrotrejo** [comment] 2024-09-05 16:05
Hi @metakahash1 I just checked and deployment is not done in all regions. It will be done by the end of the week. Please if this keeps happening after this, let me know and I will reopen the issue. To be extra sure I checked and the fix is checked in the ongoing deployment

**Comment by metakahash1** [comment] 2024-09-16 10:54
Hi @ccastrotrejo , sorry for the late reply due to my vacation. I have confirmed the fix is released!!!! I will tell this to my cx. Thank you very much!!!

**Comment by ccastrotrejo** [comment] 2024-09-16 17:30
Hi @metakahash1 I am glad it works fine now 😄
