### ISSUE TITLE
Adding Azure Functions to workflow is not working in GA Designer, not finding HTTP trigger

### ISSUE THREAD

**Issue by PedroAlmeidaMS** [Azure/LogicAppsUX#3723] opened 2023-11-20 12:37 UTC
### Describe the Bug with repro steps 

With a newly Created Azure Function, in Python Runtime, the Generally Available Designer, for Logic App Consumption, it is not able to load the HTTP trigger.

With the Preview Designer, it is working without issues.

 Batch request is loading the Function and trigger (see screenshot), but the Designer is failing to do so.

1. create Python runtime Azure Function 
2. create HTTP trigger 
3. Create Consumption LA 
4. Add Function and link to Python function 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

Old Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/112867201/b9a67946-1962-4410-b9b6-17d9eb1882c4>)

### Browser 

Edge

### Additional context 

*No response*

AB#25906357

**Comment by DanielleCogs** [comment] 2023-11-21 17:50
Confirmed this issue is only seen in GA, not in Preview

**Comment by hartra344** [comment] 2024-02-06 19:58
Closing since this is old designer only. Preview Desginer is close to moving to GA so old designer issues will only be taken on high severity issues.

**Closed by hartra344** 2024-02-06 19:58 UTC
Labels: Bug
