### ISSUE TITLE
Standard Logic App In-App Blob Connector able to select user-assigned managed identity despite it is not supported. 

### ISSUE THREAD

**Issue by LIYINDUO** [Azure/LogicAppsUX#4319] opened 2024-03-07 04:48 UTC
### Describe the Bug with repro steps 

(1) Create a user-assigned managed identity. Bind it with the standard logic app.

(2) Create a standard logic app workflow with In-App Blob trigger. Monitor that User-Assigned managed identity can be selected in the dropdownlist when creating API connection.

![image](<https://github.com/Azure/LogicAppsUX/assets/19198958/f1ae12de-a5e2-4212-ba3d-7ec6d3a9bf4d>)

(3) Upon testing. We found despite UserMI is selected. The Logic App will still try to access the Storage with System-MI.

 Meaning that the selection is not actually working, and if we disable System-MI or remove its role permission. The Logic App would run into an abnormal state, workflows unable to display workflows at portal and trigger is not firing.

(4) Kindly evaluate, it might be applicable to disable the selection for User-Assigned managed identity when creating In-App blob API connection at Designer Portal.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome.

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-03-07 22:15
Hi @LIYINDUO, we currently have a fix that might be related that is rolling out currently, it should be live in all regions by EoD tomorrow, let's have you try your repro again after the rollout is complete and see if that fixes it for you.  The rollout should be complete by noon PST if you want to try after then and let me know if it did / didn't get fixed and we can investigate further.
I'm unable to repro with your steps in both the current release and in the fixed release so I'm not 100% on that but we'll see.

**Comment by LIYINDUO** [comment] 2024-03-08 03:12
@rllyy97 Hello. Well received. I'll try again after tomorrow and keep you informed.

**Comment by LIYINDUO** [comment] 2024-03-13 10:05
@rllyy97  Issue seems to be still present testing today. Sent the session ID to you via Teams chat.

**Comment by rllyy97** [comment] 2024-03-20 18:45
@LIYINDUO I'm unable to reproduce the behavior you're describing.
I created a new app, added the same trigger, created a connection using a user-assigned identity.
Going back to the app's connections and opening the created connection, the details show the same user-identity I selected previously.
Can you retry the connection creation in your app, and then verify the correct identity is selected in the connections data itself?
If the connections data shows the user-identity and the app is still using the system identity then this is something on the backend.

**Comment by rllyy97** [comment] 2024-03-25 15:27
Discussed the issue offline, will be working on a fix.

**Comment by rllyy97** [comment] 2024-03-29 20:25
It doesn't look like we have any information on the api object we get indicating that we shouldn't allow user identities in the MI connections for this connector.  Ideally for something like this we'd like there to be some sort of info on the connector to describe that limitation, rather than putting something in for this one specific connector on the frontend.  If something like that is given to us in the connector info we can adjust but until then I don't think we'll be making any changes on our side.

**Comment by preetriti1** [comment] 2024-05-01 21:33
THis is fixed by #4662

**Closed by preetriti1** 2024-05-01 21:33 UTC
Labels: Bug, Connections
