### ISSUE TITLE
Sharepoint List folder Action not encoding URL Properly

### ISSUE THREAD

**Issue by okiejake** [Azure/LogicAppsUX#5477] opened 2024-08-22 22:52 UTC
### Describe the Bug with repro steps 

Previously the action would encode the URL with percent encoding (%252f, %2b) for the "File Identifier" param. Now the action does not seem to be doing this and it is resulting in 404 errors. I've worked around the issue and verified this is the problem by manually encoding the File Identifier with percent encoding and getting a successful run.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

MacOS

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment] 2024-08-23 04:31
@okiejake - I am not able to repro this issue with List Folder action in LA consumption (east us)
![image](https://github.com/user-attachments/assets/aafd18a5-6a26-4a27-8a11-705dd943d5e2)

We get this information from sharepoint and we use that value itself, there is no extra encoding done on this content by designer. if you still see this issue, please send me your network traces captured before you start browsing and select the folder up till then and share with me psamband@microsoft.com

**Comment by mbarqawi** [comment] 2024-08-27 13:31
@preetriti1 

- select folder by browser
- switch to code make sure that the path is encoded
- then try to modify the path by hand 
- then switch to code view and note the  encoding is not applied 

**expected result** 
the value should be encoded 



![msedge_ihHcm3PDcp](https://github.com/user-attachments/assets/e5024973-ec5c-4197-be7b-8e8f34876b03)

**Comment by okiejake** [comment] 2024-08-27 17:10
> @preetriti1
> 
> * select folder by browser
> * switch to code make sure that the path is encoded
> * then try to modify the path by hand
> * then switch to code view and note the  encoding is not applied
> 
> **expected result** the value should be encoded
> 
> ![msedge_ihHcm3PDcp](https://private-user-images.githubusercontent.com/891607/361823873-e5024973-ec5c-4197-be7b-8e8f34876b03.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzg2NjEsIm5iZiI6MTcyNDc3ODM2MSwicGF0aCI6Ii84OTE2MDcvMzYxODIzODczLWU1MDI0OTczLWVjNWMtNDE5Ny1iZTdiLThlOGYzNDg3NmIwMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjI2Y2VkNTYxNWUwOTA5ZTRhYTAzODZlMzAxZDEwZWRjOTdlNGRiYTNlNTkyM2E2OTExMzI2YWE5ZWNiNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8oind9l_kxZpQnuWJ75E7ZU8praRMQxdR-23e7lcjQ) [ ![msedge_ihHcm3PDcp](https://private-user-images.githubusercontent.com/891607/361823873-e5024973-ec5c-4197-be7b-8e8f34876b03.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzg2NjEsIm5iZiI6MTcyNDc3ODM2MSwicGF0aCI6Ii84OTE2MDcvMzYxODIzODczLWU1MDI0OTczLWVjNWMtNDE5Ny1iZTdiLThlOGYzNDg3NmIwMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjI2Y2VkNTYxNWUwOTA5ZTRhYTAzODZlMzAxZDEwZWRjOTdlNGRiYTNlNTkyM2E2OTExMzI2YWE5ZWNiNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8oind9l_kxZpQnuWJ75E7ZU8praRMQxdR-23e7lcjQ) ](https://private-user-images.githubusercontent.com/891607/361823873-e5024973-ec5c-4197-be7b-8e8f34876b03.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzg2NjEsIm5iZiI6MTcyNDc3ODM2MSwicGF0aCI6Ii84OTE2MDcvMzYxODIzODczLWU1MDI0OTczLWVjNWMtNDE5Ny1iZTdiLThlOGYzNDg3NmIwMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjI2Y2VkNTYxNWUwOTA5ZTRhYTAzODZlMzAxZDEwZWRjOTdlNGRiYTNlNTkyM2E2OTExMzI2YWE5ZWNiNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8oind9l_kxZpQnuWJ75E7ZU8praRMQxdR-23e7lcjQ) [ ](https://private-user-images.githubusercontent.com/891607/361823873-e5024973-ec5c-4197-be7b-8e8f34876b03.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Nzg2NjEsIm5iZiI6MTcyNDc3ODM2MSwicGF0aCI6Ii84OTE2MDcvMzYxODIzODczLWU1MDI0OTczLWVjNWMtNDE5Ny1iZTdiLThlOGYzNDg3NmIwMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjI2Y2VkNTYxNWUwOTA5ZTRhYTAzODZlMzAxZDEwZWRjOTdlNGRiYTNlNTkyM2E2OTExMzI2YWE5ZWNiNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C8oind9l_kxZpQnuWJ75E7ZU8praRMQxdR-23e7lcjQ)

Thank you @mbarqawi, that is the issue we are facing exactly. In our case we can not select the correct folder in the browser tool. Once we go more than 3 folders deep the site crashes. As a solution we had manually updated the folder path using the editable field in the step but it gets rid of the encoding.

**Comment by preetriti1** [comment] 2024-08-29 16:58
@okiejake @mbarqawi - The issue is what you see is just a displayName in folder picker... there is an actual value which your sharepoint list says it has that is the encoded path... client would not know how to encode it... so sharepoint needs to encode and send it back
if you are seeing the crash we will have to work on that bug, but doing the manual editing you take it away from UI and your edited value will be taken as source of truth.... the encodeUriCOmponent maybe can encode it during your runtime, but once user edits it we should not magically encode it to main user edited value

**Comment by preetriti1** [comment] 2024-09-13 04:24
@okiejake - The designer treats all path parameters like file identifier here are always added a default encoding which API specifies, that is why we add the encodeURIComponent in designer since in runtime it will be used that way...

Anything else cannot be added without proper definition from API connector for specific parameter, that is how the design is. To cater to your ask I would suggest to open a ticket with Sharepoint connector and see what they suggest, this wont be just Logic Apps at this moment.
I will be closing this issue now.

**Closed by preetriti1** 2024-09-13 04:24 UTC
Labels: Needs More Info
