### ISSUE TITLE
Error in test connection for SFTP: "Failed to create connection, encountered Internal Server Error"

### ISSUE THREAD

**Issue by S-Jindal** [Azure/LogicAppsUX#2064] opened 2023-04-19 05:54 UTC
### Describe the Bug with repro steps

(Need to test with SFTP connector's backend changes for test connection in manifest deployed on Azure)

1. Use any action or trigger from SFTP built in connector
2. Add server details (any) and click on Create connection. 
3. Inspect the network trace

### Screenshots or Videos

![Screenshot 2023-03-23 113809](https://user-images.githubusercontent.com/29829222/232978896-465471b2-9d47-435a-896c-752f002e7b7a.jpg)

### Browser

Chrome

### Additional context

Make the backend changes for test connection in the BPM repo in SFTP connector's ServiceOperation object, so that designer recognizes that this connector supports test connection and initiates the test when you click on save during connection creation.

Deploy the changes and test. The payload is being sent incorrectly.

**Comment by rllyy97** [comment] 2023-05-03 21:08
This issue was fixed in the following PR: https://github.com/Azure/LogicAppsUX/pull/2062
This functionality should be working as intended in our current release

**Closed by rllyy97** 2023-05-03 21:08 UTC
Labels: Prerelease API
