### ISSUE TITLE
Error when adding send grid connection in Standard Logic Apps

### ISSUE THREAD

**Issue by bryanm0204** [Azure/LogicAppsUX#4302] opened 2024-03-04 08:58 UTC
### Describe the Bug with repro steps 

1. Create a new workflow for any standard logic app. 
2. Add send email action under send grid. 
3. Input your API key. 
4. It can't create the connection. See screenshot. 
5. No issue adding the same action in consumption logic app. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![SendGrid](<https://github.com/Azure/LogicAppsUX/assets/162107329/764da111-cd5f-420a-94bf-47e44e47e0b5>)

### Browser 

Microsoft Edge

### Additional context 

Create a new workflow, any starting trigger (recurrence is fine). It's the connection in send grid that is the issue. Same steps is working successfully in consumption logic app.

**Comment by hartra344** [comment] 2024-03-04 16:46
Duplicate of #4260 

This is a problem with the connector that the connector owner has to fix. We’ve sent this to that team already but there’s nothing we can do directly until they fix it.

**Closed by hartra344** 2024-03-04 16:46 UTC

**Comment by bryanm0204** [comment] 2024-03-05 02:44
> Duplicate of #4260
> 
> This is a problem with the connector that the connector owner has to fix. We’ve sent this to that team already but there’s nothing we can do directly until they fix it.

When you mention connector owner, you mean sendgrid?
