### ISSUE TITLE
Parallel branches which "run after" multiple parallel actions render very awkwardly

### ISSUE THREAD

**Issue by ek68794998** [Azure/LogicAppsUX#5587] opened 2024-09-03 19:16 UTC
### Describe the Bug with repro steps

1. Add a trigger
2. Add an Initialize Variable action
3. Add a parallel branch from trigger w/ a new Initialize Variable action
4. Add another parallel branch from trigger w/ a new Initialize Variable action
5. Add a Current Time action on one of the branches
6. Add another Current Time action after the one in step 5
7. Set the Run After configuration for both Current Time actions to be after all 3 Initialize Variable actions succeed

What actually happens:
![image](https://github.com/user-attachments/assets/aff150ac-997f-4ea3-8402-17701e9536ee)

What I would expect:
![image](https://github.com/user-attachments/assets/4c12ddd3-1d95-4ed1-82c9-478ffdfa2f4f)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Which operating system are you using?

Windows

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {
      "Initialize_variable": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "",
              "type": "boolean"
            }
          ]
        },
        "runAfter": {}
      },
      "Initialize_variable_1": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "",
              "type": "boolean"
            }
          ]
        },
        "runAfter": {}
      },
      "Initialize_variable_2": {
        "type": "InitializeVariable",
        "inputs": {
          "variables": [
            {
              "name": "",
              "type": "boolean"
            }
          ]
        },
        "runAfter": {}
      },
      "Current_time": {
        "type": "Expression",
        "kind": "CurrentTime",
        "inputs": {},
        "runAfter": {
          "Initialize_variable_2": [
            "SUCCEEDED"
          ],
          "Initialize_variable_1": [
            "SUCCEEDED"
          ],
          "Initialize_variable": [
            "SUCCEEDED"
          ]
        }
      },
      "Current_time-copy": {
        "type": "Expression",
        "kind": "CurrentTime",
        "inputs": {},
        "runAfter": {
          "Initialize_variable_1": [
            "SUCCEEDED"
          ],
          "Initialize_variable": [
            "SUCCEEDED"
          ],
          "Initialize_variable_2": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "interval": 3,
          "frequency": "Minute"
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Browser

- Browser: Chrome 128.0.6613.86 x64
- OS: Windows 11

**Comment by rllyy97** [comment] 2024-09-03 19:22
This sort of behavior is pretty tricky from just first impressions, and it also cuts out a couple places users might want to add nodes.
ie. if you want to add a node between a specific parent and a specific child that isn't possible with your example solution.
I do agree it renders very awkward/bad, but I'm not sure what a better option would be with this configuration of run afters.
I'm not sure this is a very common use-case as well so I'm not sure it's worth investigating for the amount of time/effort it would take.

**Comment by rllyy97** [comment] 2024-09-03 19:29
I think there's bound to be some overlap, even if we changed the line shape there's still edge button/midpoint overlap just because of the layout of the nodes.
![image](https://github.com/user-attachments/assets/ba349af7-ffe7-428f-8ce4-6e5b7544d3df)

**Comment by rllyy97** [comment] 2024-09-23 15:59
Closing this as it is expected behavior, maybe we can start a discussion instead but I'm not sure what can be done here.

**Closed by rllyy97** 2024-09-23 15:59 UTC
Labels: Feature Request
