### ISSUE TITLE
Unable to access full blob file structure

### ISSUE THREAD

**Issue by JohnScrapp** [Azure/LogicAppsUX#5334] opened 2024-08-08 14:57 UTC
### Describe the Bug with repro steps 

When utilizing any Azure blob Storage related actions, I personally was using Lists Blobs (V2) and Get Blob Content (V2). Whenever I or my colleague would attempt to navigate to the lowest level of the folder structure the logic app designer would freeze and become unresponsive and eventually error out.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/user-attachments/assets/5a5d7f29-59ff-4447-9be7-cb714feb0de0>)

![image](<https://github.com/user-attachments/assets/e5c9dc31-f422-4c9e-a89c-f156def53553>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-08-08 15:14
Hi @johnscrapp, thanks for reporting your issue, this does appear to be a duplicate of another issue found here: https://github.com/Azure/LogicAppsUX/issues/5324
I'm going to close this one, but please follow the other item for updates from us!

**Closed by rllyy97** 2024-08-08 15:14 UTC
