### ISSUE TITLE
Logic App Azure Api Manager shape can not be initialized after forcing a minimum API version on Azure api manager.

### ISSUE THREAD

**Issue by RobertM021** [Azure/LogicAppsUX#4841] opened 2024-05-14 12:40 UTC
### Describe the Bug with repro steps

1. On your Azure API Manager, set the required API version on "yes" with minimum API version on the proposed "2021-08-01".
2. Turning this setting on, will break the designtime from a logic app that uses the API Call shapes with the error: 
Unable to initialize operation details for operation -xxxxxxxxxxxx Error details - API version query parameter is not specified or was specified incorrectly. Supported versions: 2021-08-01,2021-12-01-preview,2022-04-01-preview,2022-08-01,2022-09-01-preview,2023-03-01-preview,2023-05-01-preview,2023-09-01-preview Example query param format: api-version=SupportedVersion

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

**Comment by hartra344** [comment] 2024-05-15 03:36
I think this is a duplicate of #3385

**Closed by hartra344** 2024-05-15 03:36 UTC

**Comment by RobertM021** [comment] 2024-05-15 07:50
Hi Travis,

It is is. However, there is still no solution , as the initial ticket was crreated in september 2023.....

regards,

Robert M

________________________________
Van: Travis Harris ***@***.***>
Verzonden: woensdag 15 mei 2024 5:36
Aan: Azure/LogicAppsUX ***@***.***>
CC: RobertM021 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Azure/LogicAppsUX] Logic App Azure Api Manager shape can not be initialized after forcing a minimum API version on Azure api manager. (Issue #4841)


I think this is a duplicate of #3385<https://github.com/Azure/LogicAppsUX/issues/3385>
