### ISSUE TITLE
VS Code can't open workflow in designer

### ISSUE THREAD

**Issue by PeterSchults** [Azure/LogicAppsUX#1998] opened 2023-04-13 08:27 UTC
### Describe the Bug with repro steps

- switch workflow designer to preview
- Same issue when i open workflow in VSC

### Screenshots or Videos

![Schermafbeelding 2023-04-13 102527](https://user-images.githubusercontent.com/16748614/231700384-ab37c4a9-0453-41bd-8f9c-f584c6b0ec3a.png)

### Browser

- Chrome
- Edge

### Additional context

Same problem when i open this workflow in VSC
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by hartra344** [comment] 2023-04-13 16:32
duplicate of #1934

**Closed by hartra344** 2023-04-13 16:32 UTC
