### ISSUE TITLE
Action configuration pane of the 'Start approval when a new item is added' template are in loading state on designer page.

### ISSUE THREAD

**Issue by pranaydubeymicrosoft** [Azure/LogicAppsUX#3969] opened 2024-01-11 18:31 UTC
### Describe the Bug with repro steps

1. login to https://make.preprod.powerautomate.com/
2. Navigate to template page, search for 'Start approval when a new item is added' template
3. open it, create valid connections and click continue.
4. v3 designer page opens with the template and copilot loads valid connections
5. click on trigger and fill the required fields, select the site address
6. the left-side pane closes, again click on trigger to fill parameters.
7. observe

### What type of Logic App Is this happening in?

Power Automate

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/135278983/87308a0a-a652-438f-9cb7-87250292c846)

### Browser

Edge

### Additional context

Original bug: [Bug 26243584](https://msazure.visualstudio.com/One/_workitems/edit/26243584): [make.preprod]Action configuration pane of the 'Start approval when a new item is added' template are in loading state on designer page.

**Comment by rllyy97** [comment] 2024-01-11 20:54
Hi @pranaydubeymicrosoft, I'm unable to reproduce this behavior following the steps you gave, was there anything else you might have done to cause this?

**Comment by ek68794998** [comment] 2024-01-11 21:08
@rllyy97 When you attempted to repro, were you using LA standalone, LA portal, or PA portal?

**Comment by rllyy97** [comment] 2024-01-11 21:17
PA Portal, Travis brought me into the conversation you all were having as well.
I saw you mentioned you were seeing the `nodesInitialized` redux value get set to false, it looks like the only time we set that value is with the exported actions `resetWorkflowState` or with `resetNodesLoadStatus`.
Are you all calling one of those actions on your side?

**Comment by ek68794998** [comment] 2024-01-11 21:39
> Are you all calling one of those actions on your side?

Let me double-check.

> PA Portal, Travis brought me into the conversation you all were having as well.

Makes sense; I forgot to mention that in the meantime, we reverted the package out (it's back on 2.89.1) so you can't reproduce in preprod. :( If you'd like to validate the change yourself, I can create an endpoint that you can test on pretty easily.

**Comment by hartra344** [comment] 2024-01-12 18:47
Closing here since the issue is actually a bug on the PA side calling reset. If we find other issues along the way we can file them seperately

**Closed by hartra344** 2024-01-12 18:47 UTC
Labels: Needs More Info, triage
