### ISSUE TITLE
Http trigger schema changed in new designer

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#4170] opened 2024-02-12 18:19 UTC
### Describe the Bug with repro steps 

Using the new logic app designer, workflow with http triggered as saved as node name "When\_a\_Http\_request\_is\_received". however, in old designer, it will save as "manual". Is this expected change?

For http trigger,

in new designer, the workflow trigger saved as node name.

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/9f94f536-1963-4c15-8b1e-78d85a7ba551>)

in old designer, it will save as "manual"

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/5b3e0aca-8c4d-46bc-8bf1-65cc04e96caf>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by hartra344** [comment] 2024-02-13 19:58
Checked into it. This is by design, manual was a misleading name and the name is not how the functionality is decided. It will function exactly the same.

**Closed by hartra344** 2024-02-13 19:58 UTC

**Comment by Xiaoyu-Huang** [comment] 2024-02-13 22:22
@hartra344  Not just the property name, the new designer is missing inputs as well. Is this also an expected change?
`{
inputs: 
{
 'schema': {}
}
}`
