### ISSUE TITLE
Azure Logic apps (Standard) extension on Visual Code

### ISSUE THREAD

**Issue by AymanEnter** [Azure/LogicAppsUX#3777] opened 2023-11-30 15:48 UTC
### Describe the Bug with repro steps

When Creating a logic app on the workspace from visual code I got a popup with the following information:
files is not iterable
Source: Azure logic apps (Standard)(Extension)
![image](https://github.com/Azure/LogicAppsUX/assets/152515953/4f5a228d-9407-493e-bd8b-bfe9d82f6b1e)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/152515953/c3980861-792a-4b18-a7c3-254968250fa5)

### Browser

Chrome

AB#26009365

**Comment by hartra344** [comment] 2023-11-30 15:49
duplicate of #3777 , closing this one and you can track progress on that one. We're actively working on the issue.

**Closed by hartra344** 2023-11-30 15:49 UTC
Labels: triage
