### ISSUE TITLE
Unable to edit expressions in the new designer

### ISSUE THREAD

**Issue by ian-harmon-navistar** [Azure/LogicAppsUX#4464] opened 2024-03-27 14:07 UTC
### Describe the Bug with repro steps 

In any scenario when trying to create an expression, or edit an existing expression made in the legacy designer, no expression is shown in the preview box where the expression should be. This occurs when clicking on new expression elements, trying to type into the expression box, or viewing existing expressions made in the legacy designer. The expression creator pop-up also looks strange color-wise, possibly because I am in dark mode.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/165175400/39cbe3da-42d6-41e1-b400-016fe29a1097>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by ian-harmon-navistar** [comment] 2024-03-27 14:21
it seems that it works fine in Edge after waiting a moment for the text box to load, however it still never appears after wiping all of chrome's data and waiting a substantial period.

![image](https://github.com/Azure/LogicAppsUX/assets/165175400/977ebe38-f42f-4f01-8fb8-3e65e63e39b1)

**Comment by hartra344** [comment] 2024-03-27 16:29
I think this should be fixed with Eric's change the other day

**Comment by hartra344** [comment] 2024-03-27 16:41
Also could be fixed with the monaco change. I can't tell if it's a CDN failure or the theming. @rllyy97 can we get an up to date designer into a private/hotfix slot so this person can see if it's fixed for them?

**Comment by Eric-B-Wu** [comment] 2024-03-27 18:25
Yeah this looks like a combination of not having dark support (I think this was a regression because I know we previously did have this) and also CDN fetch being delayed. We have fixes in for both, so hopefully both will no longer be an issue in the newest release

**Comment by Eric-B-Wu** [comment] 2024-04-23 15:56
Both these changes changes should now be released. Please let me know if there are any issues and I can reopen to address.

**Closed by Eric-B-Wu** 2024-04-23 15:56 UTC
Labels: Bug, Tokens
