### ISSUE TITLE
Missing values on the UI but present in the code

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#1702] opened 2023-03-02 22:48 UTC
### Describe the Bug

I have created a workflow using VSCode where I am calling another workflow hosted in the same logic app and passing the required parameters. When the code is published to Azure, I see the call workflow action but the parameters go missing on the UI but it's seen in the underlying code.

### Steps to Reproduce the Bug or Issue

1. Create two logic app standard workflows in VSCode
2. call one workflow - "exceptions handler" and allow the HTTP trigger to accept input parameters.
3. from the 2nd workflow, call the exception handler workflow and pass some values as parameters.
4. publish the code to Azure DevOps --> deploy to --> Azure Logic App Standard
5. open the 2nd workflow, go to the call-workflow action and see if the parameters are still shown.

### Expected behavior

Whatever I see on VSCode UI, I should be able to see the exact same thing in Azure workflow UI

### Platform And Browser

- OS: [Windows]
- Browser: [Edge]

AB#17409527

**Comment by mhireholi** [comment] 2023-03-06 15:51
@Eric-B-Wu: The workflow was created on the Visual Studio code designer (local) and everything looks fine there. When the code is published to Azure and I go to the portal to see it, I notice the parameters and the values in the Call workflow actions have disappeared.

**Comment by preetriti1** [comment] 2023-04-19 20:29
@mhireholi - I was able to successfully deploy the parent-child workflow from vscode to Azure and view the same parameters in Azure portal. There might be some issues in the vscode extension in not showing all parameters for child workflow correctly today and that should be fixed in coming days.
But I do not see the parameters not appearing in portal issue yet.
Can you try this with latest extension and show us some screenshots both in vscode UI and portal?

**Comment by preetriti1** [comment] 2023-04-20 18:58
Closing this issue since it is not reproducible

**Closed by preetriti1** 2023-04-20 18:58 UTC
