### ISSUE TITLE
Drag and drop into subgraphs doesn't work

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2126] opened 2023-04-25 16:55 UTC
### Describe the Bug with repro steps

See screenshot
![las-designer-bug-scope-shape](https://user-images.githubusercontent.com/40304643/234348571-13299c32-5c2c-46af-b3ac-5d91b3726fc3.jpg)

### Screenshots or Videos

![las-designer-bug-scope-shape](https://user-images.githubusercontent.com/40304643/234348629-291916d5-a317-4ffa-bf5c-0d4d73a2f44e.jpg)

### Browser

VS Code
Edge
Chrome

**Comment by Eric-B-Wu** [comment] 2023-05-10 00:05
oh @hartra344 forgot to leave a comment here, but this was caused by a change that prevented nodes with output tokens to be dragged above parent. I think in the brownbag we just wanted to make sure if this was an unintended case and not a feature

**Comment by rllyy97** [comment] 2023-05-19 15:28
Closing with regards to new known issue tracker https://github.com/Azure/LogicAppsUX/issues/2455

**Closed by rllyy97** 2023-05-19 15:28 UTC
Labels: Bug
