### ISSUE TITLE
Data Mapper not displaying map anymore

### ISSUE THREAD

**Issue by your-azure-coach** [Azure/LogicAppsUX#5305] opened 2024-08-07 07:07 UTC
### Describe the Bug with repro steps 

The Data Mapper does not visualize maps anymore. Instead, we get a black screen.

Two ways to reproduce.

1. When creating a new map and selecting a schema 

![DataMapper-NewMap](<https://github.com/user-attachments/assets/4ac7a503-9990-480d-8204-3231de75d53c>)

2. When opening an existing map 

![DataMapper-ExistingMap](<https://github.com/user-attachments/assets/8e4c9bc5-52c6-4fc1-be76-0a510067c8be>)

 \`\`

### Screenshots or Videos 

*No response*

### Version 

v4.44.8, rolling back to v4.31.7 resolves the issue, in v4.44.7 the issue is already present

### Additional context 

Two days ago, the maps opened successfully on my computer and also on the one of my colleague. Since this morning, maps are not being displayed anymore.

Thanks for your help on this one!

**Comment by hartra344** [comment] 2024-08-07 14:57
This one looks like a bug rather than a usability problem being fixed with the new DM. @DanielleCogs , can you take a look

**Comment by DanielleCogs** [comment] 2024-08-07 16:02
Hello @your-azure-coach we identified the issue as new in version 4.44.8, and are in the process of deploying a fix in 4.44.9 that should be complete by EOD. If you are unable to see the new version, you can revert here https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurelogicapps to version 4.31.7 to temporarily unblock.

**Comment by DanielleCogs** [comment] 2024-08-07 16:17
Confirmed 4.44.9 is working as expected, you can install the update from the extension tab in VSCode

**Closed** 2024-08-08 16:00 UTC
Labels: Data Mapper
