### ISSUE TITLE
Logic App Preview Designer - HTTP Web Request Save error and manual code changes 

### ISSUE THREAD

**Issue by jme107** [Azure/LogicAppsUX#2596] opened 2023-05-30 10:12 UTC
### Describe the Bug with repro steps

Start the generally available designer
1. step create a rest request 
2.  Request Microsoft Graph API (teams with Filter) 
3.  Add the following Web Reqest https://graph.microsoft.com/beta/teams?filter=displayName eq 'Test Team' (see screenshots)
4. Click Safe : Error: Failed to safe Logic App Logicapp1. Definition contains invalid parameters. 
5. Click Code view and safe then it works 

Why in the preview with a correct web request an error is thrown in the designer and the saving is not possible, is already a bug and shows that the implementation of requests with filters etc. is not provided, but let's come to the actually critical problem. 

Start Preview Designer
1. step create a rest request 
2.  Request Microsoft Graph API (teams with Filter) 
3.  Add the following Web Reqest https://graph.microsoft.com/beta/teams?filter=displayName eq 'Test Team' (see screenshots)
4. the save button is disabled and it cannot be saved
5. Click Code view: the code view on the right side opens (probably in bad scaling and only on the right edge which limits the usablility enormously) and it is no longer possible to save in the code view
Therefore also correct web requests can not be saved and used in the future

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![logicapp ga designer](https://github.com/Azure/LogicAppsUX/assets/55663282/c045c094-90c6-4e59-9750-2d23ad1c4320)
![logicapppreivew designer](https://github.com/Azure/LogicAppsUX/assets/55663282/00fac759-8065-461b-b20f-1a52056c9b57)

### Browser

- Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)
- Firefox 113.0.2 

### Additional context

If the new preview designer is implemented in this way, manual code chancing will no longer be possible and you will have to rely on the syntax detection in Logic App to work, which unfortunately it does not. 

From my point of view, this means that Logic Apps can unfortunately no longer be used in the future and unfortunately the workflows must be migrated to a product of a competitor. 

AB#24187930

**Comment by preetriti1** [comment] 2023-05-30 14:38
@Eric-B-Wu - This seems to be a uri validation issue, can we work in the new designer to fix this?
This doesn't seem like it was working foe the customer ever since they have shown screenshots of both old and new designer, so not a regression but new bug.

**Comment by Eric-B-Wu** [comment] 2023-05-30 22:32
Hi @jme107 thanks for creating the issue and bringing to our attention that there's a mismatch in URL validation between frontend and backend, let me confirm with our backend team and I'll try to get this fixed in our next release in the preview designer ETA  6/9

**Comment by itpropro** [comment] 2023-05-30 23:11
This also results in multiple problems with the new editor, as it seems like you cannot save with the mentioned characters in the URI field. In the old experience, you were able to switch to the code view and save from there.
In the new experience, the code view is squished on the left and makes reading or even working on that code impossible. Even worse, the functionality to be able to save as long as the code is valid, even when the designer has errors, seems to be gone as well.
Please keep the code view as it is now, the current design is a huge downgrade for the code viewer.

**Comment by jme107** [comment] 2023-05-30 23:12
Hi @Eric-B-Wu  Thanks for your feedback. 

Would it be useful to allow code view editing and saving in the new designer ? This concerns not only API request, but it is also sometimes necessary to store and save line breaks etc. in the CodeView. 
Furthermore, I think it would be more practical if the CodeView opens over the whole page and not only on the right side.

**Comment by preetriti1** [comment] 2023-06-02 23:18
> This also results in multiple problems with the new editor, as it seems like you cannot save with the mentioned characters in the URI field. In the old experience, you were able to switch to the code view and save from there. In the new experience, the code view is squished on the right and makes reading or even working on that code impossible. Even worse, the functionality to be able to save as long as the code is valid, even when the designer has errors, seems to be gone as well. Please keep the code view as it is now, the current design is a huge downgrade for the code viewer.

Codeview was never visible in LA standard apps with old designer, that was a feature only for Consumption. In the new designer you could atleast view it in codeview, we will discuss with our team if we need this feature in LA standard workflows.
for now we will only track this issue for fixing the URL validation.

**Comment by itpropro** [comment] 2023-08-24 14:35
> > This also results in multiple problems with the new editor, as it seems like you cannot save with the mentioned characters in the URI field. In the old experience, you were able to switch to the code view and save from there. In the new experience, the code view is squished on the right and makes reading or even working on that code impossible. Even worse, the functionality to be able to save as long as the code is valid, even when the designer has errors, seems to be gone as well. Please keep the code view as it is now, the current design is a huge downgrade for the code viewer.
> 
> Codeview was never visible in LA standard apps with old designer, that was a feature only for Consumption. In the new designer you could atleast view it in codeview, we will discuss with our team if we need this feature in LA standard workflows. for now we will only track this issue for fixing the URL validation.

That there was no code view for Standard was already a huge issue, as there are so many bugs in the trigger and action validations that most complex workflows can only be saved in code view or via json deployment. Please don't make the code viewer even worse and duplicate existing issues, like the missing code view, with the new UI. The code viewer is an essential part of creating and maintaining logic apps and should not be treated as a secondary feature that is hard to use.

**Closed** 2023-09-20 18:58 UTC
Labels: Bug, Feature Request, Consumption, Work Item
