### ISSUE TITLE
Logic app designer not loading in VS Code

### ISSUE THREAD

**Issue by giancarloQ** [Azure/LogicAppsUX#5737] opened 2024-09-24 10:57 UTC
### Describe the Bug with repro steps 

Once I open the designer for the workflow .json the error below appears:

settingValue.startsWith is not a function

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Check_Guru_Api_Proxy": {
                "type": "Scope",
                "actions": {
                    "HTTP_Guru_Api_Proxy_Healthcheck": {
                        "type": "Http",
                        "inputs": {
                            "uri": "@replace(appsetting('GuruApiProxyUrl'), '/proxy/', '/healthcheck')",
                            "method": "GET",
                            "headers": {
                                "x-functions-key": "@{appsetting('GuruApiProxyFunctionKey')}"
                            }
                        },
                        "runtimeConfiguration": {
                            "contentTransfer": {
                                "transferMode": "Chunked"
                            }
                        }
                    },
                    "Set_variable_canConnectGuruApi": {
                        "type": "SetVariable",
                        "inputs": {
                            "name": "canConnectGuruApiProxy",
                            "value": true
                        },
                        "runAfter": {
                            "HTTP_Guru_Api_Proxy_Healthcheck": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "runAfter": {
                    "Check_Junifer_API": [
                        "SUCCEEDED",
                        "TIMEDOUT",
                        "SKIPPED",
                        "FAILED"
                    ]
                }
            },
            "Check_Junifer_API": {
                "type": "Scope",
                "actions": {
                    "HTTP_Junifer_Bearer_Token": {
                        "type": "Http",
                        "inputs": {
                            "uri": "@{appsetting('JuniferApiUrl')}token",
                            "method": "POST",
                            "authentication": {
                                "password": "@{appsetting('JuniferApiPassword')}",
                                "type": "Basic",
                                "username": "@{appsetting('JuniferApiUsername')}"
                            }
                        },
                        "operationOptions": "SuppressWorkflowHeaders",
                        "runtimeConfiguration": {
                            "contentTransfer": {
                                "transferMode": "Chunked"
                            }
                        }
                    },
                    "Set_variable_canConnectJuniferApi": {
                        "type": "SetVariable",
                        "inputs": {
                            "name": "canConnectJuniferApi",
                            "value": true
                        },
                        "runAfter": {
                            "HTTP_Junifer_Bearer_Token": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "runAfter": {
                    "Initialize_variable_canConnectJuniferSftp": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Check_Junifer_SFTP": {
                "type": "Scope",
                "actions": {
                    "List_folder": {
                        "type": "ServiceProvider",
                        "inputs": {
                            "parameters": {
                                "folderPath": "/"
                            },
                            "serviceProviderConfiguration": {
                                "connectionName": "sftpJunifer",
                                "operationId": "listFolder",
                                "serviceProviderId": "/serviceProviders/Sftp"
                            },
                            "retryPolicy": {
                                "type": "none"
                            }
                        }
                    },
                    "Set_variable_canConnectSftp": {
                        "type": "SetVariable",
                        "inputs": {
                            "name": "canConnectJuniferSftp",
                            "value": true
                        },
                        "runAfter": {
                            "List_folder": [
                                "SUCCEEDED"
                            ]
                        }
                    }
                },
                "runAfter": {
                    "Check_Guru_Api_Proxy": [
                        "SUCCEEDED",
                        "TIMEDOUT",
                        "SKIPPED",
                        "FAILED"
                    ]
                }
            },
            "Compose_Response": {
                "type": "Compose",
                "inputs": {
                    "configuration": {
                        "guruApiProxy": {
                            "baseUrl": "@{appsetting('GuruApiProxyUrl')}"
                        },
                        "juniferApi": {
                            "baseUrl": "@{appsetting('JuniferApiUrl')}"
                        },
                        "juniferSftp": {
                            "hostAddress": "@{appsetting('JuniferSftpSshHostAddress')}",
                            "portNumber": "@{appsetting('JuniferSftpPortNumber')}"
                        }
                    },
                    "dependencyHealthchecks": {
                        "guruApiProxy": "@body('HTTP_Guru_Api_Proxy_Healthcheck')"
                    },
                    "status": {
                        "guruApiProxy": "@{variables('canConnectGuruApiProxy')}",
                        "juniferApi": "@{variables('canConnectJuniferApi')}",
                        "juniferSftp": "@{variables('canConnectJuniferSftp')}"
                    }
                },
                "runAfter": {
                    "Check_Junifer_SFTP": [
                        "SUCCEEDED",
                        "TIMEDOUT",
                        "SKIPPED",
                        "FAILED"
                    ]
                }
            },
            "Initialize_variable_canConnectGuruApi": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "canConnectGuruApiProxy",
                            "type": "boolean",
                            "value": false
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_variable_canConnectJuniferApi": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Initialize_variable_canConnectJuniferApi": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "canConnectJuniferApi",
                            "type": "boolean",
                            "value": false
                        }
                    ]
                },
                "runAfter": {}
            },
            "Initialize_variable_canConnectJuniferSftp": {
                "type": "InitializeVariable",
                "inputs": {
                    "variables": [
                        {
                            "name": "canConnectJuniferSftp",
                            "type": "boolean",
                            "value": false
                        }
                    ]
                },
                "runAfter": {
                    "Initialize_variable_canConnectGuruApi": [
                        "SUCCEEDED"
                    ]
                }
            },
            "Response": {
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": "@if(and(variables('canConnectJuniferApi'),variables('canConnectGuruApiProxy'),variables('canConnectJuniferSftp')),200,503)",
                    "body": "@outputs('Compose_Response')"
                },
                "runAfter": {
                    "Compose_Response": [
                        "SUCCEEDED"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "method": "GET"
                }
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](<https://github.com/user-attachments/assets/0f7100e1-2eaa-4760-b6fa-6fafb336ca1e>)

### Browser

Using visual studio code

### Additional context

*No response*

**Comment by hartra344** [comment] 2024-09-24 16:22
duplicate of #5736

**Closed by hartra344** 2024-09-24 16:22 UTC
