### ISSUE TITLE
Slack Plugin to send Message is throwing error while saving the Logic App.

### ISSUE THREAD

**Issue by himanshusaini-fa** [Azure/LogicAppsUX#2861] opened 2023-06-27 14:34 UTC
### Describe the Bug with repro steps

Create a Step To send Message on a Slack Channel.

Login to Slack and Allow The Required Permissions on the workspace

Select your channel name. Enter any text for message

Save it and it will throw an error: 
![image](https://github.com/Azure/LogicAppsUX/assets/67495938/fb74548b-5b1d-4a01-b638-629965e02baa)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "frequency": "Day",
          "interval": 1,
          "schedule": {
            "hours": [
              "7"
            ]
          },
          "timeZone": "India Standard Time"
        }
      }
    },
    "actions": {
      "For_each_3": {
        "type": "Foreach",
        "foreach": "@body('Report_DB')?['resultsets']?['Table1']",
        "actions": {
          "Post_message_(V2)_3": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "referenceName": "slack"
                }
              },
              "method": "post",
              "body": {
                "channel": "C05DTQXCVQV",
                "text": "DayStarts Synced to Report DB: @{items('For_each_3')?['DSCount']}"
              },
              "path": "/v2/chat.postMessage"
            }
          }
        },
        "runAfter": {
          "For_each_4": [
            "Succeeded"
          ]
        }
      },
      "For_each_4": {
        "type": "Foreach",
        "foreach": "@body('Transaction_DB')?['resultsets']?['Table1']",
        "actions": {
          "Post_message_(V2)_4": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "referenceName": "slack"
                }
              },
              "method": "post",
              "body": {
                "channel": "C05DTQXCVQV",
                "text": "Valid DayRecods: @{items('For_each_4')?['ValidDayRecords']}\n\nDistinct Users with DayRecords: @{items('For_each_4')?['DistinctESMDayStarts']}"
              },
              "path": "/v2/chat.postMessage"
            }
          }
        },
        "runAfter": {
          "Report_DB": [
            "Succeeded"
          ]
        }
      },
      "Report_DB": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['sql-2']['connectionId']"
            }
          },
          "method": "post",
          "body": {
            "query": "SELECT COUNT(DayStartDateKey) DSCount from DayStarts where DayStartDateKey = CONVERT(CHAR(8), DATEADD(d,-1,GETUTCDATE()),112) and ModifiedBy != 'MissingDaystartProcessor'"
          },
          "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('FA_Reports'))}/query/sql"
        },
        "runAfter": {
          "Transaction_DB": [
            "Succeeded"
          ]
        }
      },
      "Transaction_DB": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['sql-3']['connectionId']"
            }
          },
          "method": "post",
          "body": {
            "query": "SELECT COUNT(*) ValidDayRecords, COUNT(Distinct EmployeeId) DistinctESMDayStarts from DayRecords where QualifiedDate = CONVERT(CHAR(8), DATEADD(d,-1,GETUTCDATE()),112) and IsInvalid = 0"
          },
          "path": "/v2/datasets/@{encodeURIComponent(encodeURIComponent('default'))},@{encodeURIComponent(encodeURIComponent('default'))}/query/sql"
        },
        "runAfter": {}
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "slack": {
          "connectionId": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/resourceGroups/rg-india-internal/providers/Microsoft.Web/connections/slack",
          "connectionName": "slack",
          "id": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/providers/Microsoft.Web/locations/centralindia/managedApis/slack"
        },
        "sql-2": {
          "connectionId": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/resourceGroups/rg-india-internal/providers/Microsoft.Web/connections/sql-2",
          "connectionName": "sql-2",
          "id": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/providers/Microsoft.Web/locations/centralindia/managedApis/sql"
        },
        "sql-3": {
          "connectionId": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/resourceGroups/rg-india-internal/providers/Microsoft.Web/connections/sql-3",
          "connectionName": "sql-3",
          "id": "/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/providers/Microsoft.Web/locations/centralindia/managedApis/sql"
        }
      }
    }
  }
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/67495938/eb99fc6c-d8c2-4c7a-881f-7c95cc3d200a)

### Browser

Brave: Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)

AB#24388315

**Comment by rllyy97** [comment] 2023-06-27 19:06
@himanshusaini-fa thanks for the bug report, however I am unable to reproduce this behavior when following your repro steps (in both standard and consumption).  For me to look into this further it would help if you could send us a network trace of you trying to save your app.
You can follow steps to do that here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file
And you can send the collected network trace `.har` file to me at rileyevans@microsoft.com

**Comment by himanshusaini-fa** [comment] 2023-06-28 14:13
@rllyy97 I have sent the Requested har File on the email Id Provided.

As I could see, 

https://management.azure.com/subscriptions/a61f85e9-5461-4772-9add-46e5e1b93613/resourceGroups/rg-india-internal/providers/Microsoft.Logic/workflows/Log-DataSync-Details?api-version=2016-10-01

Above API was throwing 400 with the Message Given in the Screenshot

**Comment by himanshusaini-fa** [comment] 2023-06-28 14:25
In this APIs Body

I Changed

                                    {
                                    "connection": {
                                        "referenceName": "slack"
                                    }
                                    
To:

                                    {
                                    "connection": {
                                        "name": "slack"
                                    }
                                    
The API Returned success and Apparently, the changes got saved. But the Logic App was unreadable by Front End

![image](https://github.com/Azure/LogicAppsUX/assets/67495938/bee0c277-39d2-424e-85c8-25f996373b3f)

**Comment by himanshusaini-fa** [comment] 2023-06-28 14:28
Now I Changed it to 
                                        "name": "@parameters('$connections')['slack']['connectionId']"
                                        
Now the API was a success and my gibberish changes reflected.

**Comment by rllyy97** [comment] 2023-06-28 19:40
I found the problem!  Realized this was a duplicate of https://github.com/Azure/LogicAppsUX/issues/2837 since your slack action is nested in a for-loop, I am working on a fix for it now 👍

**Comment by rllyy97** [comment] 2023-06-29 15:45
This has been fixed and will be fully rolled out to production by July 7th

**Closed by rllyy97** 2023-06-29 15:45 UTC
Labels: Bug
