### ISSUE TITLE
Bug in Encodian connector

### ISSUE THREAD

**Issue by ManuelStern** [Azure/LogicAppsUX#4133] opened 2024-02-06 17:33 UTC
### Describe the Bug with repro steps 

1. in a new Logic App Consumption, add an HTTP request trigger 
2. add an Encodian Convert Excel action 
3. You can use an Encodian connection with invalid fieldws 
4. Populate the fields and try to save it 

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/1fd1220f-9f7c-4d9d-8747-db25d5e0ebba>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Convert_Excel": {
                "inputs": {
                    "body": {
                        "exportHiddenSheets": false,
                        "fileContent": "@{base64(triggerBody())}",
                        "fileName": "filename.xsl",
                        "outputFilename": "word",
                        "outputFormat": "",
                        "removeDocumentMarkup": true
                    },
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['encodiandocumentmanager']['connectionId']"
                        }
                    },
                    "method": "post",
                    "path": "/api/v1/Core/ConvertExcel",
                    "queries": {
                        "outputFormatParameter": "XLSX"
                    }
                },
                "runAfter": {},
                "type": "ApiConnection"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "parameters": {
            "$connections": {
                "defaultValue": {},
                "type": "Object"
            }
        },
        "triggers": {
            "manual": {
                "inputs": {
                    "schema": {}
                },
                "kind": "Http",
                "type": "Request"
            }
        }
    },
    "parameters": {
        "$connections": {
            "value": {
                "encodiandocumentmanager": {
                    "connectionId": "/subscriptions/fb6a0986-ac32-4056-af38-0b87d1224db0/resourceGroups/newLogicAppmstern_group/providers/Microsoft.Web/connections/encodiandocumentmanager-2",
                    "connectionName": "encodiandocumentmanager-2",
                    "id": "/subscriptions/fb6a0986-ac32-4056-af38-0b87d1224db0/providers/Microsoft.Web/locations/westeurope/managedApis/encodiandocumentmanager"
                }
            }
        }
    }
}
```

### Screenshots or Videos

We add an action Encodian Convert Excel. This is from a third party company, Encodian.

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/98898ee6-16a3-47ab-8956-3e6faf0a01e2>)

If we try to save this from the designer, we get an error "output format is required"

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/b9a8b758-40cd-4577-b0df-ff917e384b2c>)

However, we can save it from Code View.

It seems the output format is not populated by the designer, although we set it in the drop down. If we peek the code:

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/fd755007-dee9-49a1-87df-20633774f230>)

We can change the code in code view itself by setting the OutputFormat per hand

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/1d2e3605-16bf-4c72-a1d7-a6f06b74b96f>)

If you change that, then it will also be changed in the designer, and the workflow can be saved.

![image](<https://github.com/Azure/LogicAppsUX/assets/142807001/332c1ba3-a5db-4c7a-87c4-3e9b69e0db67>)

There

### Browser

Edge

### Additional context

*No response*

**Comment by hartra344** [comment] 2024-02-06 19:08
This is a duplicate of #4120

**Closed by hartra344** 2024-02-06 19:08 UTC
