### ISSUE TITLE
The renderComponentIntoRoot component encountered an error while loading in logic app standard

### ISSUE THREAD

**Issue by saroja-sattigeri** [Azure/LogicAppsUX#5775] opened 2024-09-27 09:11 UTC
### Describe the Bug with repro steps 

Go to Logic App standard in Azure Portal, go to run history if you click on run id in current tab/page customer could see run however, if they click ctlr+left mouse button it will take to new tab and gives below error(customer wants to open in new tab/page)

![image](<https://github.com/user-attachments/assets/5b4cc4e8-b6d4-47b4-bb15-6fcffe1e660c>)

However, customer can see run history in new tab(if they click ctrl+left mouse button) via old designer url [https://aka.ms/lafallback](<https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2faka.ms%2flafallback&data=05%7c01%7csasatti%40microsoft.com%7cd225a387a19540fd5a7e08db5c051b23%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638204949435775580%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=P51sjV3MmO%2BtFo%2B5ogkcM4Pz%2BkvNwME46vNC67m3ohY%3D&reserved=0>)

From extension analyzer, i see below

![image](<https://github.com/user-attachments/assets/1ce083a7-4689-4691-8b7a-730a80135289>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by Eric-B-Wu** [comment] 2024-09-30 19:03
closing as a duplicate of https://github.com/Azure/LogicAppsUX/issues/5671; I have been unable to reproduce, but based on the console error I've created a change which I think may fix the issue that will be going out next deployment

**Closed by Eric-B-Wu** 2024-09-30 19:03 UTC
