### ISSUE TITLE
Select from Array Action - Mapping Not being displayed property

### ISSUE THREAD

**Issue by axiomitdavid** [Azure/LogicAppsUX#2034] opened 2023-04-17 01:29 UTC
### Describe the Bug with repro steps

When using a Select action to select specified properties from one array into another, the expression used is displayed properly initially.  On re-opening the workflow, the mapping is not displayed correctly, the JSON representation appears to be valid.

1. Workflow with Sharepoint Get Items action
2. Select Action to obtain specific values from the results of the Get Items
 - Using item()?['fieldname'] expression
 3. Save workflow and reopen
 4. Viewing the Select action shows invalid information

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Get_CW": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "sharepointonline"
                        }
                    },
                    "method": "get",
                    "path": "/datasets/@{encodeURIComponent(encodeURIComponent(parameters('sp_list_url')))}/tables/@{encodeURIComponent(encodeURIComponent(appsetting('sp_list_id_cw_customers')))}/items",
                    "queries": {
                        "$filter": "Status  eq 'Active'",
                        "$top": 4999
                    }
                },
                "runAfter": {}
            },
            "Select_AAD": {
                "type": "Select",
                "inputs": {
                    "from": "@body('Get_AAD')?['value']",
                    "select": {
                        "DefaultDomainName": "@{item()?['DefaultDomainName']}",
                        "Domains": "@{item()?['Domains']}",
                        "TenantID": "@{item()?['TenantID']}",
                        "TenantName": "@{item()?['TenantName']}"
                    }
                },
                "runAfter": {
                    "Get_AAD": [
                        "Succeeded"
                    ]
                }
            },
            "Select_CW": {
                "type": "Select",
                "inputs": {
                    "from": "@body('Get_CW')?['value']",
                    "select": {
                        "AxiomCLOUD": "@{item()?['AxiomCLOUD']}",
                        "TenantID": "@{item()?[parameters('sp_list_field_name_aad_tenantid')]}",
                        "TenantName": "@{item()?[parameters('sp_list_field_name_aad_tenantname')]}"
                    }
                },
                "runAfter": {
                    "Get_CW": [
                        "Succeeded"
                    ]
                }
            },
            "Inner_Join_on_TenantID": {
                "type": "JavaScriptCode",
                "inputs": {
                    "code": "function joinArrays(array1, array2) {\n  let result = [];\n\n  for (let i = 0; i < array1.length; i++) {\n    for (let j = 0; j < array2.length; j++) {\n      if (array1[i].TenantID === array2[j].TenantID) {\n        result.push(Object.assign({}, array1[i], array2[j]));\n      }\n    }\n  }\n\n  return result;\n}\n\nconst arr1 = workflowContext.actions.Select_AAD.outputs.body;\nconst arr2 = workflowContext.actions.Select_CW.outputs.body;\n\nconst result = joinArrays(arr1, arr2);\nreturn result;"
                },
                "runAfter": {
                    "Select_AAD": [
                        "Succeeded"
                    ]
                }
            },
            "Did_Domain_get_specified_": {
                "type": "If",
                "expression": {
                    "and": [
                        {
                            "not": {
                                "equals": [
                                    "@empty(triggerBody()?['domain'])",
                                    true
                                ]
                            }
                        }
                    ]
                },
                "actions": {
                    "Return_Domian": {
                        "type": "Response",
                        "kind": "http",
                        "inputs": {
                            "statusCode": 200,
                            "body": "@body('Filter_down_to_domain_in_question')"
                        },
                        "runAfter": {
                            "Filter_down_to_domain_in_question": [
                                "Succeeded"
                            ]
                        }
                    },
                    "Filter_down_to_domain_in_question": {
                        "type": "Query",
                        "inputs": {
                            "from": "@outputs('Inner_Join_on_TenantID')",
                            "where": "@contains(item()?['Domains'], triggerBody()?['domain'])"
                        }
                    }
                },
                "else": {
                    "actions": {
                        "Return_All_Rows": {
                            "type": "Response",
                            "kind": "http",
                            "inputs": {
                                "statusCode": 200,
                                "body": "@outputs('Inner_Join_on_TenantID')"
                            }
                        }
                    }
                },
                "runAfter": {
                    "Parse_Joined_Data": [
                        "Succeeded"
                    ]
                }
            },
            "Parse_Joined_Data": {
                "type": "ParseJson",
                "inputs": {
                    "content": "@outputs('Inner_Join_on_TenantID')",
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "DefaultDomainName": {
                                    "type": "string"
                                },
                                "Domains": {
                                    "type": "string"
                                },
                                "TenantID": {
                                    "type": "string"
                                },
                                "TenantName": {
                                    "type": "string"
                                },
                                "AxiomCLOUD": {
                                    "type": "boolean"
                                }
                            },
                            "required": [
                                "DefaultDomainName",
                                "Domains",
                                "TenantID",
                                "TenantName",
                                "AxiomCLOUD"
                            ]
                        }
                    }
                },
                "runAfter": {
                    "Inner_Join_on_TenantID": [
                        "Succeeded"
                    ]
                }
            },
            "Get_AAD": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "sharepointonline"
                        }
                    },
                    "method": "get",
                    "path": "/datasets/@{encodeURIComponent(encodeURIComponent(parameters('sp_list_url')))}/tables/@{encodeURIComponent(encodeURIComponent(appsetting('sp_list_id_aad_tenants')))}/items"
                },
                "runAfter": {
                    "Select_CW": [
                        "Succeeded"
                    ]
                }
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "manual": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "domain": {
                                "type": "string"
                            },
                            "all": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

Initial Experience
![image](https://user-images.githubusercontent.com/41350688/232357102-b2eecfc7-d776-4ce3-b285-4929da2cca5b.png)

After Re-Opening
![image](https://user-images.githubusercontent.com/41350688/232357168-41cf1443-95ea-4e0f-a1d3-1c46c8ae4053.png)

### Browser

VS Code 1.73.1
Logic Apps Standard Designer 2.3.0

**Comment by hartra344** [comment] 2023-04-17 03:56
@Eric-B-Wu is this one of the issues you just fixed the other day?

**Comment by Eric-B-Wu** [comment] 2023-04-19 22:14
hmm never mind, I'm not able to reproduce the second issue, so it seems like it should be fixed. 

As for the first issue, this is a known issue in: 
tokensegment.ts
// TODO - Implement for item tokens when repetition context is in store.

**Closed by Eric-B-Wu** 2023-04-19 22:14 UTC
Labels: bug
