### ISSUE TITLE
Failed to Retrieve Dynamic Inputs - New Designer

### ISSUE THREAD

**Issue by Squarepour** [Azure/LogicAppsUX#2951] opened 2023-07-11 19:43 UTC
### Describe the Bug with repro steps

For Logic App Standard (not consumption).  Problem connecting to On-Premises Data Gateway to SQL Server.

1. Open Design view (New Designer) of Logic App Standard workflow.
2. Scroll down to previously functional Actions that depend on On-Premise Data Gateway (such as Execute stored procedure (V2)).  
3. Note the red warning text "Failed to Retrieve Dynamic Inputs".
4. Click on the action, see further description:  "Failed to Retrieve Dynamic Inputs.  Error Details: ''  "
5. Try to rebuild new Action.
6. Drop down fields that populate Server name, Database name, etc. do not populate with any options.
7. Note that the Connections screen shows the status of the connection is "Connected".
8. Note that the application itself running on the server shows "your gateway is all set up".
9. Note that the warning disappears when forcing use of Old Designer.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome and Edge.

AB#24508440

**Comment by rllyy97** [comment] 2023-07-12 23:18
Hi @Squarepour , thank you for the bug report!  We recently released a dynamic data fix for the broader issue mentioned here https://github.com/Azure/LogicAppsUX/issues/2949, and I am fairly confident this issue has the same root cause.  I am going to close this issue, but feel free to try out your use case and if you are still experiencing issues let us know and we can reopen and investigate further.

**Closed by rllyy97** 2023-07-12 23:18 UTC
Labels: Dynamic Data
