### ISSUE TITLE
Can't create and run a new standard logic app from VS Code

### ISSUE THREAD

**Issue by TimothyMDean** [Azure/LogicAppsUX#5221] opened 2024-07-29 21:12 UTC
### Describe the Bug with repro steps 

Trying to create a new logic app and run/debug in VS code. Created a new logic app:

1. From Azure tab, under Workspace section, click on Azure Logic Apps button then Create new project 
2. Enter in required folder location and information - Allow default "Stateful" workflow to be created 
3. Open new workflow in designer - verify that designer comes up with no actions or triggers 
4. Try to run/debug using the F5 key 
5. See error: 

```
:\Program Files\dotnet\dotnet.exe C:\Users\TimMDean\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.70.96\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll 

Generating debug symbols...
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.GenerateDebugSymbols(String debugAssemblyOutPath)
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Execute()
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Main(String[] args)
```

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Not using a browser directly - running in VS Code

### Additional context 

I originally encountered this problem when trying to export an existing consumption logic app into a new standard logic app project. After fixing some of the required steps (e.g. deploying managed connection) I got the designer to come up, but running always failed.

Tried to recreate with a new project unrelated to the original consumption logic app, but still unable to start the logic app locally.

**Comment by ccastrotrejo** [comment] 2024-07-29 23:19
Hi @TimothyMDean thanks for raising this issue. The error that you pasted about not being able to debug the assembly symbols from the vscode extension, usually when this error happens while running the logic app locally the breakpoints doesn't work, however the project still is able to run. I will take a look on how to solve this for now, but this shouldn't stop you to run the logic app.

By any chance do notice any other error? maybe in the console or output channel? 

Could you please execute in the vscode terminal with your logic apps project open, the following command? /Users/<your username>/.azurelogicapps/dependencies/FuncCoreTools/func host start --verbose

**Comment by TimothyMDean** [comment] 2024-07-29 23:56
@ccastrotrejo Here is the contents of the output channel:

```
4:02:50 PM: Running command: "C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start --port 8000" with pid: "15340"...

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554


Functions:

	NetFxLanguageWorkerFunction: NetFxTrigger

	XsltNetFxLanguageWorkerFunction: NetFxTrigger

For detailed output, run func with --verbose flag.
[2024-07-29T21:03:05.886Z] Worker process started and initialized.
[2024-07-29T21:03:09.147Z] Host lock lease acquired by instance ID '0000000000000000000000000B865648'.
4:03:32 PM: Running command: "C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func GetExtensionBundlePath"...
4:03:45 PM: Extension bundle path: "C:\Users\TimMDean\.azure-functions-core-tools\Functions\ExtensionBundles\"...
4:03:52 PM: Error: Error exists after running preLaunchTask "func: host start". View task output for more information.
```
The Debug Console is blank.

It doesn't appear to me that the application is running at all, so it's not just affecting the breakpoints. The terminal also includes this:

```
Generating debug symbols...
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.GenerateDebugSymbols(String debugAssemblyOutPath)
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Execute()
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Main(String[] args)

 *  The terminal process "C:\Program Files\dotnet\dotnet.exe 'C:\Users\TimMDean\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.70.96\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll'" terminated with exit code: -532462766. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start 

bash: C:UsersTimMDean.azurelogicappsdependenciesFuncCoreToolsfunc: command not found

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', 'C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start'" terminated with exit code: 127. 
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

**Comment by ccastrotrejo** [comment] 2024-07-30 22:54
Ok, yes it seems that the error that is throwing says that the func command doesn't exist but for the first screenshot it seems that is indeed getting executed. 
Does the following path exists in your computer? is there content on that folder?
 C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools

**Comment by sneakyflint** [comment] 2024-07-31 05:30
Just wanted to share that I am seeing similar behavior re: the debug process failing, though I am able to run `func host start` without issues. It seems like bundle version 1.70.96 for Microsoft.Azure.Functions.ExtensionBundle.Workflows is the culprit of the debugging issue.

Reverting to 1.70.60 based on the list [here](https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/index-v2.json) has resolved the issue for me.

The VS Code extension does not seem to respect the extensionBundle version set in host.json, but I was able to get it to cooperate as follows:
1. Update host.json to downgrade the Logic Apps extension bundle version:
```
...
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.0.0, 1.66.20)"
  }
``` 
2. Run the launch.json task for "Attach to .NET Functions" and receive the debug error. Allow the core tools to finish starting so that the downgraded bundle is downloaded
3. Remove the 1.70.96 bundle from disk, for me this was located in `$HOME/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.70.96`
4. Run the launch.json task again and debug symbols should now generate as expected on the downgraded extension bundle

**Comment by TimothyMDean** [comment] 2024-07-31 13:33
@ccastrotrejo Yes, that directory does exist on my workstation. And as @sneakyflint points out, the `func host start` command does run when I run from the command line. I just can't use F5 or Run/Debug menu option.

**Comment by TimothyMDean** [comment] 2024-07-31 14:09
@sneakyflint Thanks for the suggested workaround. It seemed to help a little - the step to generate debug symbols worked once reverting back to version 1.66.20. However, the subsequent `func host start` command failed. It appeared to be running the func command from the `$HOME/.azurelogicapps/dependencies/FuncCoreTools` directory but got a "command not found" error.

I tried removing my `.azurelogicapps/dependencies` folder and allow it to re-download, but that seems to have forced me back to version 1.70.96. That version keeps getting re-downloaded and used no matter what I try to undo it. So now I am once again stuck where I was before: I can run `func host start` manually from the command line, but not via F5 and I can't debug.

**Comment by ccastrotrejo** [comment] 2024-07-31 17:25
Hi @sneakyflint thanks for the provided workaround. This workaround does work for downloading the right extension bundle that doesn't have the issue with attaching the assembly files. This happens when we want to run and debug the logic app project with the Run/Debug menu option. 
@TimothyMDean The workaround for now is to follow the step from @sneakyflint above or just press F5 and run the logic app project, since it seems that debugging with the lastes extension bundle doesn't work.

However if running the option with just F5 doesn't work that its a different issue.
Does the `/.azurelogicapps/dependencies/FuncCoreTools` has content on it? Does it has a `func` executable in it?
Is there any error when you press F5? besides the command not found? Is there any chance I can get a screenshot?
If the func executable exists I don't see why it is happening. Is there any chance you can share your project zipped over email? My email is ccastrotrejo@microsoft.com


I will work with the backend team to solve the issue of not being able to debug it correctly.

**Comment by TimothyMDean** [comment] 2024-07-31 20:52
> @TimothyMDean The workaround for now is to follow the step from @sneakyflint above or just press F5 and run the logic app project, since it seems that debugging with the lastes extension bundle doesn't work.

Unfortunately, the workaround from @sneakyflint isn't working for me. It seemed to work for a brief moment, but something is forcing my VS code to keep re-installing and using version 1.70.96 to generate debug symbols. For example, here is the command and output I receive right now:

```
Executing task: C:\Program Files\dotnet\dotnet.exe C:\Users\TimMDean\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.70.96\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll 

Generating debug symbols...
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.GenerateDebugSymbols(String debugAssemblyOutPath)
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Execute()
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Main(String[] args)

 *  The terminal process "C:\Program Files\dotnet\dotnet.exe 'C:\Users\TimMDean\.azure-functions-core-tools\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle.Workflows\1.70.96\bin\Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll'" terminated with exit code: -532462766. 
```

As you can see, it is still using version 1.70.96 no matter what I do. I have deleted it multiple times and repeated the steps from the workaround above, but this broken version keeps coming back.

Now, when I try to run without debugging (Ctrl-F5) it skips the step to generate debug symbols. Instead, it just tries to run `func host start`. But it gets errors as well:

```
Executing task: C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start 

bash: C:UsersTimMDean.azurelogicappsdependenciesFuncCoreToolsfunc: command not found

 *  The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-i', '-c', 'C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start'" terminated with exit code: 127. 
```

The `func.exe` executable does exist in `C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools`  so not sure why the above command is failing. If I enter the `func host start` directly command from the command line it works just fine:

```
$ func host start

Azure Functions Core Tools
Core Tools Version:       4.0.5907 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit)
Function Runtime Version: 4.834.3.22875


Functions:

        WorkflowDispatcher: edgeWorkflowRuntimeTrigger

For detailed output, run func with --verbose flag.
[2024-07-31T20:38:56.250Z] Host lock lease acquired by instance ID '0000000000000000000000000B865648'.
```
I did look at the specific versions of the `func` executable being used. When I just type `func host start` I believe I am getting it from `C:\Program Files\Microsoft\Azure Functions Core Tools\func` - appearing to be version 4.0.5907 of the core tools. When I explicitly run the version from `C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func` it also runs, but it is version 4.0.5455 of the core tools.

Both appear to work when I run in the command line. Neither appears to work when running through the `bash` command that is used when I use the F5 or Ctrl-F5 to run. And neither seems to be debuggable at this time due to the debug symbol issue noted above (that I can't workaround using the steps @sneakyflint because version 1.70.96 keeps getting re-installed for some reason.

**Comment by ccastrotrejo** [comment] 2024-08-05 23:23
Hi all, I reached out to the back end team and the first issue about not being able to debug the logic app project properly will be resolved in the upcoming weeks. A new extension bundle with the fix will be released.

**Comment by ccastrotrejo** [comment] 2024-08-05 23:38
However, @TimothyMDean your second issue is unrelated to the first one. I really can't catch what can be the reason on why this is failing, besides not being able to find the `func` executable in the right path. Is there any chance you can send me your zipped project to my email: ccastrotrejo@microsoft.com

Also when does this started happening?

**Comment by TimothyMDean** [comment] 2024-08-06 22:11
I have emailed you a zip file with my project that is encountering this issue.

I do not know when this started. This is the first time I have tried to run a logic app locally in VS Code in about 6 months. At that time, I was able to run/debug a logic app using F5, and when I tried again a week or two ago, I got this problem right away. But I have no way of knowing if something else has changed in my local VS code environment since that time.

**Comment by TimothyMDean** [comment] 2024-08-07 14:13
@ccastrotrejo The email server on the Microsoft side rejects an email with the zip file attached, so it doesn't sound like an option for troubleshooting. Please advise on what else I can do to figure out how to make things work again.

**Comment by sneakyflint** [comment] 2024-08-07 20:37
@TimothyMDean What is the your VS Code default shell set to? Based on the error you posted it seems like it is Git bash, but Windows paths are being passed to the terminal:
`C:\Users\TimMDean\.azurelogicapps\dependencies\FuncCoreTools\func host start`

Bash is treating the `\` as an escape character, which is why you are seeing that error:
`bash: C:UsersTimMDean.azurelogicappsdependenciesFuncCoreToolsfunc: command not found`

Guessing that the `func` task type in `.vscode/tasks.json` does not expect a Linux-based terminal on Windows systems. I would try updating your default shell to PowerShell and see if the behavior persists, or try using [remote development in WSL](https://code.visualstudio.com/docs/remote/wsl) if you need a Linux shell as your default.

**Comment by ccastrotrejo** [comment] 2024-08-07 20:52
Hi @sneakyflint thanks for the suggestion, yep that might be the error. I noticed it as well, it seems that the bash is trying to execute the `func` from the path without the escape characters.

@TimothyMDean Could you please give it a try updating your default shell to powershell?

**Closed** 2024-08-08 22:05 UTC
Labels: VSCode

**Comment by TimothyMDean** [comment] 2024-08-12 14:27
Thanks @sneakyflint and @ccastrotrejo - I was able to confirm that the additional problem I was encountering goes away when I change my default terminal to not use Git bash.

**Comment by ccastrotrejo** [comment] 2024-08-12 16:56
@TimothyMDean I am glad it worked out!

**Comment by sneakyflint** [comment] 2024-08-19 03:35
Hi @ccastrotrejo - happy Monday. We are seeing this same error pop up again when on the latest version of the extension bundle, has this symbol issue been reintroduced? 
Same language re: System.Collections.Immutable:
``` *  Executing task in folder src: dotnet /home/vscode/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows/1.81.25/bin/Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.dll 

Generating debug symbols...
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.GenerateDebugSymbols(String debugAssemblyOutPath)
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Execute()
   at Microsoft.Azure.Workflows.BuildTasks.DebugSymbolGenerator.DebugSymbolGenerator.Main(String[] args)
 *  Terminal will be reused by tasks, press any key to close it. 
 ```
 
 Thanks in advance 😄

**Comment by jeanpaulsmit** [comment] 2024-08-21 15:21
Same here, using 1.81.25

**Comment by ccastrotrejo** [comment] 2024-08-21 15:53
Hi @jeanpaulsmit and @sneakyflint thanks for noticing it and letting us know. It seems like a regression, I will let the backend team about it. Thanks!

**Comment by ccastrotrejo** [comment] 2024-08-21 17:07
Hi all, I talked with the team and the fix for this will released later this week. 
The workaround for now might be to downgrade the version of it.
