### ISSUE TITLE
Unable to save Logic App

### ISSUE THREAD

**Issue by Dimeji98** [Azure/LogicAppsUX#2421] opened 2023-05-18 13:44 UTC
### Describe the Bug with repro steps

1. I make a change and save it
2. I receive the standard notification that the changes has been saved.
3. But the save button is still clickable afterwards and when I go to exit the Logic App it is giving me the notification that the unsaved edits will be discarded

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Chrome

**Comment by rllyy97** [comment] 2023-05-18 22:56
Hi @Dimeji98, thanks for the bug report!  This is most likely a duplicate of https://github.com/Azure/LogicAppsUX/issues/2388, and we're aiming to have this fixed in our next release

**Closed by rllyy97** 2023-05-18 22:56 UTC
