### ISSUE TITLE
Can't save basic logic app in new (preview) editor

### ISSUE THREAD

**Issue by MrSimonC** [Azure/LogicAppsUX#2887] opened 2023-06-30 09:50 UTC
### Describe the Bug with repro steps

1. Create a new logic app & use the new preview designer
2. Add a trigger (e.g. recurrence)
3. Add in "List all Shifts" (from Microsoft Shifts
4. Save
5. Logic app saves successfully
6. Add in new step "Get a Shift"
7. Provide "Get a shift" action with a valid Team, and choose Shift ID input as "Shift Id" from the "List all shifts" action
8. Logic app creates the for-each loop for you
9. Click Save

Expected:
Logic App saves correctly

Actual:
Failes to save with error message:
`Workflow validation failed for the workflow ''. {"error":{"code":"BadRequest","message":"The API connection name must be provided in the 'Get_a_Shift' action inputs."}}`

Workaround:
Use Legacy Designer

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "triggers": {
      "Recurrence": {
        "type": "Recurrence",
        "recurrence": {
          "frequency": "Week",
          "interval": 1,
          "schedule": {
            "hours": [
              "9"
            ],
            "weekDays": [
              "Monday"
            ]
          }
        }
      }
    },
    "actions": {
      "List_all_Shifts": {
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['shifts']['connectionId']"
            }
          },
          "method": "get",
          "path": "/v1.0/teams/@{encodeURIComponent('d8c23bdc-c053-4a5e-a588-4295919ba284')}/schedule/shifts"
        },
        "runAfter": {}
      },
      "For_each": {
        "type": "foreach",
        "foreach": "@body('List_all_Shifts')?['value']",
        "actions": {
          "Get_a_Shift": {
            "type": "ApiConnection",
            "inputs": {
              "host": {
                "connection": {
                  "referenceName": "shifts"
                }
              },
              "method": "get",
              "path": "/v1.0/teams/@{encodeURIComponent('d8c23bdc-c053-4a5e-a588-4295919ba284')}/schedule/shifts/@{encodeURIComponent(items('For_each')?['id'])}"
            }
          }
        },
        "runAfter": {
          "List_all_Shifts": [
            "SUCCEEDED"
          ]
        }
      }
    },
    "outputs": {},
    "parameters": {
      "$connections": {
        "type": "Object",
        "defaultValue": {}
      }
    }
  },
  "parameters": {
    "$connections": {
      "value": {
        "shifts": {
          "connectionId": "/subscriptions/6bc77dd7-d619-4774-a068-1761adac19ef/resourceGroups/digital-solutions-inbox/providers/Microsoft.Web/connections/shifts",
          "connectionName": "shifts",
          "id": "/subscriptions/6bc77dd7-d619-4774-a068-1761adac19ef/providers/Microsoft.Web/locations/westeurope/managedApis/shifts"
        }
      }
    }
  }
}
```

### Browser

Microsoft Edge latest GA version (114.0.1823.58 (Official build) (64-bit))

### Additional context

Thanks Microsoft team for your work on logic apps - I appreciate it!

AB#24422329

**Comment by rllyy97** [comment] 2023-06-30 15:16
Hi @MrSimonC , thanks for the bug report!  The root of your issue appears to be a duplicate of this issue: https://github.com/Azure/LogicAppsUX/issues/2837
We've merged a fix and it will be rolling out through next week, finishing on July 7th.
If you're still experiencing your issue after the 7th let us know and we'll take another look at it!

**Closed by rllyy97** 2023-06-30 15:16 UTC
