### ISSUE TITLE
New designer doesn't give option to pre-defined Templates . 

### ISSUE THREAD

**Issue by veeragangala** [Azure/LogicAppsUX#4446] opened 2024-03-26 12:06 UTC
### Describe the Bug with repro steps 

When we create a new Logic App, the designer doesn't take us to default templates available like in legacy designer. There is no way to check the templates like in legacy designer. Can we have them available in new designer as well.

![image](<https://github.com/Azure/LogicAppsUX/assets/44003569/faec75d4-9944-48bd-889f-875c253ba162>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
NA
```

### Screenshots or Videos

**New Designer:**

![image](<https://github.com/Azure/LogicAppsUX/assets/44003569/579aa607-db25-46f2-8e86-b14e7abd7fb7>)

**Legacy Designer:**

![image](<https://github.com/Azure/LogicAppsUX/assets/44003569/c0346a56-3f13-456a-9208-e2275a6cf55a>)

### Browser

NA

### Additional context

*No response*

**Comment by hartra344** [comment] 2024-03-26 15:05
Closing here since it’s currently by design and not a bug.

**Closed by hartra344** 2024-03-26 15:04 UTC

**Comment by divyaswarnkar** [comment] 2024-03-28 22:08
@veeragangala what specific templates are of interest to you ?
