### ISSUE TITLE
Run view shows raw HTML in outputs

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#4842] opened 2024-05-14 17:17 UTC
### Describe the Bug with repro steps

1. In Power Automate go to flows page and click on new flow -> Instant Cloud Flow
2. Flow Creation Dialog opens. Select 'Manual Trigger' and click on 'Create'.
3. V3 Designer opens with manual trigger. Click on 'Add New Action' and add 'List rows from selected environment' (Microsoft Dataverse) action.
4. Provide '(Current)' for Environment and 'Contacts' for table name and then provide select columns field value as 'firstname,lastname,fullname,annualincome'
5. Add an action 'Create HTML Table' and provide 'value/body' as the input for 'From' field.
6. In the columns field select 'custom' and add the First Name, last Name, Full Name, Annual Income and provide corresponding dynamic input values.
7. Save and test the flow.
8. Go to the flow run details page.
9. Open the create HTML table action card run details and verify the output

### What type of Logic App Is this happening in?

Power Automate

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

The issue:
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/357496aa-b38e-4734-b76f-30cce12333d1)
Previous designer view for the same:
![image](https://github.com/Azure/LogicAppsUX/assets/42044630/d6e38371-c21e-4cbc-96be-890941940ebe)

### Browser

Chrome

**Comment by hartra344** [comment] 2024-05-15 03:35
Currently working as expected, but this is a duplicate of: #4472

**Closed by hartra344** 2024-05-15 03:35 UTC
