### ISSUE TITLE
Version Blade: Unable to promote version it's currently in a disabled state

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5882] opened 2024-10-15 09:40 UTC
### Describe the Bug with repro steps 

1\.Open existing logic app in consumption.

 2\.Select any of the previous parallel version through versions blade and see switching between codeview to designer works fine.

 3\.Choose a previous parallel version and promote this version.

**Expected:** Should be able to promote version

**Actual:** Unable to promote the version because it's currently in a disabled state.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/d019d5a9-716c-45b7-8850-7f20113c677a>)

### Browser 

Edge

### Additional context 

Version: 2.41007.1.8

**Comment by Eric-B-Wu** [comment] 2024-10-15 16:48
@ccastrotrejo  this should be related to the migration to ReactView, right?

**Comment by ccastrotrejo** [comment] 2024-10-15 16:58
Yes, this is related to the migration.
However @vgouth I took a look at the logic app and the version itself. The promote button is disable because the version you are trying to promote is the most recent version. Thus we prevent user to promot the lastest version which will be the same. 

Could you please check with other versions? This should enable the promot version and you will be able to promote it.

**Comment by vgouth** [comment] 2024-10-15 17:21
@ccastrotrejo I tried with the older version. Yes, the promote button is enabled with older version. 
![Image](https://github.com/user-attachments/assets/9f52951a-4871-49e5-89d7-9ea61419089d)

**Comment by ccastrotrejo** [comment] 2024-10-15 18:23
Ok, will close this as expected by design

**Closed by ccastrotrejo** 2024-10-15 18:23 UTC
