### ISSUE TITLE
[Power Automate] Error field in Terminate actions should show conditionally

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#2052] opened 2023-04-17 23:04 UTC
### Describe the Bug with repro steps

https://msazure.visualstudio.com/One/_workitems/edit/17649685

### Browser

Chrome

**Comment by hartra344** [comment] 2023-04-17 23:07
duplicate of #1952

**Closed by hartra344** 2023-04-17 23:07 UTC
Labels: duplicate
