### ISSUE TITLE
Logic App Designer - Code changes are not being reflected in the Designer

### ISSUE THREAD

**Issue by JeremiahCollins** [Azure/LogicAppsUX#3098] opened 2023-08-07 17:32 UTC
### Describe the Bug with repro steps

The code view is not being reflected in the designer. If we save the workflow with a blank information field in the designer this will cause the code view to update the saved changes and breaks the workflow. To mitigate we have been using code view only or designer view only.

Example1

 "HTTP": {

                "inputs": {
                    "authentication": {
                        "audience": "https://graph.microsoft.us/",
                        "authority": "123",
                        "clientId": "@{guid()}",
                        "secret": "mypassword123",
                        "tenant": "XXX-XXX-XXX-XXX",
                        "type": "ActiveDirectoryOAuth"
                    },
                    "method": "GET",
                    "uri": "https://graph.microsoft.us/"
                },

In the Designer the authority shows empty. If we switch to the old designer, we see the authority values. (See Image)

![image](https://github.com/Azure/LogicAppsUX/assets/54990162/d30ede72-a7ef-47da-814f-d26788fe1d25)

The attached workflow also includes Example 2 where the base64() method is behaving the same way.

Example2

"Initialize_variable": {
                "inputs": {
                    "variables": [
                        {
                            "name": "myVar",
                            "type": "string",
                            "value": "{\n\"Key\" : \"@{base64('mysecretkey')}\"\n}"
                        }
                    ]
                },
                "runAfter": {},
                "type": "InitializeVariable"
            }

In the designer the base64 function is not represented and only the string 'mysecretkey' is represented

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "HTTP": {
                "inputs": {
                    "authentication": {
                        "audience": "https://graph.microsoft.us",
                        "authority": "123",
                        "clientId": "@{guid()}",
                        "secret": "mypassword123",
                        "tenant": "XXXX-XXX-XXX",
                        "type": "ActiveDirectoryOAuth"
                    },
                    "method": "GET",
                    "uri": "https://graph.microsoft.us"
                },
                "runAfter": {},
                "runtimeConfiguration": {
                    "contentTransfer": {
                        "transferMode": "Chunked"
                    }
                },
                "type": "Http"
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "Recurrence": {
                "recurrence": {
                    "frequency": "Week",
                    "interval": 3
                },
                "type": "Recurrence"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/54990162/68615ed2-8020-440c-bd55-aa04a228c4d2)

### Browser

EDGE

AB#24773593

**Comment by Eric-B-Wu** [comment] 2023-08-08 16:15
Hi @JeremiahCollins thanks for reporting this issue. It seems like this was caused by an issue where during deserialization of the authentication editor, an optional parameter (authority) was not parsed, hence why it was not being shown in the designer. I will have this fixed in an upcoming PR. The second part of this issue is a little trickier cause we will default uncast parameters which is what we've been doing since old designer (which means that base64 will be uncast). For this issue, if its a problem outside of auth editor, can we request you file a feature request to address

**Comment by Eric-B-Wu** [comment] 2023-08-08 18:58
closing with PR merged, changes should be reflected in 2 weeks in production

**Closed by Eric-B-Wu** 2023-08-08 18:59 UTC
