### ISSUE TITLE
Logic App Preview Designer incorrect handling of trigger arrays

### ISSUE THREAD

**Issue by shboulatom83** [Azure/LogicAppsUX#2821] opened 2023-06-22 11:36 UTC
### Describe the Bug with repro steps 

1. Create Logic App with O365 (When email arrives) trigger 
2. Try to use the Attachement name 
3. It will produce two for-eachs, which is not correct. It should create one for each. 
4. Seems the designer ignoring the Split-On property of the Trigger 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using Preview Designer or GA Designer 

Preview

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

Preview Designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/76695917/5e6313d8-df6f-4a66-9777-9a080703b77e>)

GA Designer

![image](<https://github.com/Azure/LogicAppsUX/assets/76695917/d07bc54a-3130-4467-bce5-0437258da458>)

### Browser 

All

### Additional context 

*No response*

AB#24345814

**Comment by hartra344** [comment] 2024-06-15 15:06
Closing as a duplicate of #3086 to clean up

**Closed by hartra344** 2024-06-15 15:06 UTC
Labels: Bug
