### ISSUE TITLE
'Show Logic App run details' button does not work

### ISSUE THREAD

**Issue by nicholasdemos** [Azure/LogicAppsUX#5998] opened 2024-10-31 07:57 UTC
### Describe the Bug with repro steps 

1. In GA Designer, view a logic app run that calls another logic app. 
2. Click on 'Show Logic App run details' button 
3. Designer does not do anything, and no errors reported in Edge Developer Tools 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment] 2024-10-31 14:31
Closing as duplicate of https://github.com/Azure/LogicAppsUX/issues/5999
Please follow the above issue for progress on a fix

**Closed by rllyy97** 2024-10-31 14:31 UTC
