### ISSUE TITLE
Unable to deploy Logic App - permission denied

### ISSUE THREAD

**Issue by mcollier** [Azure/LogicAppsUX#3869] opened 2023-12-18 19:12 UTC
### Describe the Bug with repro steps

1. Attempt to deploy a Logic App using the Logic App Standard extension
2. Select the desired Azure subscription and existing Logic App
3. Receive an "Error: EACCES: permission denied, mkdir '/workspaces/notification-workflow-deploytemp'" error.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/1142273/f73f9226-b272-4760-8922-ceb9beb3092e)

### Browser

N/A

### Additional context

Azure Logic Apps (Standard) v2.56.4

**VS Code**
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.23545

**Comment by ccastrotrejo** [comment] 2023-12-22 18:52
Will close this one as it was discussed internally. Root cause was that the temp folder to deploy was created with WSL, permissions might be different than the actual users permissions

**Closed by ccastrotrejo** 2023-12-22 18:52 UTC
Labels: VSCode
