### ISSUE TITLE
VS Code - Azure Pane Logic App S

### ISSUE THREAD

**Issue by JorgeCadilloCalpine** [Azure/LogicAppsUX#2508] opened 2023-05-23 17:28 UTC
### Describe the Bug with repro steps

When updating the extension to the latest version the Logic App (Standard) section disappears from the Azure Pane. Downgrading to 2.8.0 or any previous version makes it show up again.

1. Update to extension version 2.15.15.
2. Click on the Azure Pane on the left.
3. Logic App (Standard) menu disappears.

VS Code version: 1.78.2 (user setup).

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

Working version 2.0.8:

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/37ecf57b-97b0-41ee-b22b-4cbb3a75878f)

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/97b0fc0e-153f-4933-b06e-b059d1c003ca)

Non working version 2.15.15:

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/adc11934-967d-4acd-8394-ee2d8af7b064)

![image](https://github.com/Azure/LogicAppsUX/assets/134431816/fc91e2cb-1ccc-459b-9e8e-c821de1d5ac7)

### Browser

Local VS Code.

**Comment by Eric-B-Wu** [comment] 2023-05-23 17:36
Thanks for reporting this issue, this is a duplicate of https://github.com/Azure/LogicAppsUX/issues/2448, but to quote @ccastrotrejo

> Hi everyone, thank you so much for raising this issue and letting us know about this. From version 2.15.15 onwards we are following the same architecture pattern that the rest of the azure extensions are following; this implies removing our extension tab and move the remote logic apps tree structure into the resources tab in the azure panel. You will be able to see your remote apps when opening the Logic App dropdown. This also applies to the ribbon buttons that we used to have in our tab title, those were migrated to the workspace tab. We will work on updating the documentation regarding these recent changes.

> Please take a look at the following screenshot and make sure you have installed the resources tab extension version 0.7.3 or bigger
![image](https://github.com/Azure/LogicAppsUX/assets/95886809/d64d7149-6e74-4868-96f6-852ae5f0852b)

**Closed by Eric-B-Wu** 2023-05-23 17:36 UTC

**Comment by ccastrotrejo** [comment] 2023-05-23 17:42
For sure, right now we are working on updating all the documentation that points to the old flow
