### ISSUE TITLE
Can't move an action in the new designer into a control scope

### ISSUE THREAD

**Issue by rmartin-msft** [Azure/LogicAppsUX#2606] opened 2023-05-30 17:05 UTC
### Describe the Bug with repro steps

Create a new Logic App Workflow
Create a couple of regular actions, for example invoke workflow or set variables
Create a Control Scope 
Attempt to move the actions previously created into the new control scope this action is denied, but should be allowed.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Microsoft Edge

**Comment by rllyy97** [comment] 2023-05-30 17:51
Hi @rmartin-msft, thanks for the bug report!  This is a duplicate of https://github.com/Azure/LogicAppsUX/issues/2455, you can find more info on it there

**Closed by rllyy97** 2023-05-30 17:51 UTC
