### ISSUE TITLE
Saving any changes in a workflow using New Designer still prompts to unsaved changes

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2103] opened 2023-04-21 19:30 UTC
### Describe the Bug with repro steps

1. Create a new workflow using the New Designer
2. Make any changes
3. Click Save
4. Observe a confirmation pop-up:

![image](https://user-images.githubusercontent.com/351644/233719374-049b2abc-11b4-42d0-a954-13feb5ed7166.png)

5. Click Overview or Code
6. Observe an unsaved changes prompt:

![image](https://user-images.githubusercontent.com/351644/233719272-7ab9b530-794c-478b-bee6-32af1aa7221f.png)

### Workflow JSON

```json
n/a
```

### Browser

Edge version 112.0.1722.39

**Comment by Eric-B-Wu** [comment] 2023-04-21 20:03
@abatishchev Thanks for reporting this issue, this is a known issue and is happening because we currently haven't yet implemented a way of keeping track of whether the the workflow has dirtied or not, this will soon be addressed, will close this as its a duplicate of https://github.com/Azure/LogicAppsUX/issues/2036

**Closed by Eric-B-Wu** 2023-04-21 20:03 UTC
