### ISSUE TITLE
Smartsheet connection is not working in Logic Apps

### ISSUE THREAD

**Issue by nodominguez** [Azure/LogicAppsUX#5781] opened 2024-09-27 22:24 UTC
### Describe the Bug with repro steps 

Select the action to insert a row to smartsheet

 connect to your smarsheet account

 the sheets are not visible

![Screenshot 2024-09-27 162215](<https://github.com/user-attachments/assets/8e801e78-5f11-49c7-a798-639e1d0b6b71>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

Old Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
  "type": "ApiConnection",
  "inputs": {
    "host": {
      "connection": {
        "referenceName": "smartsheet"
      }
    },
    "method": "post",
    "body": "@{items('For_each')?['System.Id']}\n",
    "path": "/sheets/@{encodeURIComponent('ADO Data')}/rows"
  }
}
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by preetriti1** [comment] 2024-10-04 15:38
@nodominguez - Please use the prod designer and not old designer. If it doesn't work in that reopen this issue, we are not supporting the old designer and will be removing the entry points to it from portal.

**Comment by rllyy97** [comment] 2024-10-04 17:32
They tagged it as old designer but their screenshot appears to be new designer

**Comment by rllyy97** [comment] 2024-10-14 18:04
@nodominguez We've investigated this on our end and it appears the root of the issue is a problem with the connector configuration.  We are reaching out to the owner of the connector to get this resolved.

**Comment by rllyy97** [comment] 2024-11-08 20:37
We reached out to the connectors team and they are aware it is an issue but told us they won't be fixing it for a while.
Closing this issue since this is not on us to fix

**Closed by rllyy97** 2024-11-08 20:37 UTC
Labels: Backend
