### ISSUE TITLE
Workspace with custom code development not working after clone

### ISSUE THREAD

**Issue by skastberg** [Azure/LogicAppsUX#5620] opened 2024-09-09 21:15 UTC
### Describe the Bug with repro steps 

1. Create a project as described [here](<https://learn.microsoft.com/en-us/azure/logic-apps/create-run-custom-code-functions>) 
2. Ensure everything is working nicely in your environment 
3. Commit the code to a repository, as is … 
4. Clone the repository to another machine or another folder 
5. Open the workspace, note that you're not able to debug. 
6. Note that **local.settings.json** is missing as it is excluded as it is in ignore files. 
7. Note that `lib`, `obj` and `bin` folders are committed to the repository 

> Some related discussions in #5458

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

- Edge Version **128\.0.2739.67** (Official build) (64-bit) 
- Core Tools Version: **4\.0.5907** Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (64-bit) 
- Function Runtime Version: **4\.834.3.22875** 
- Functions Extension **1\.15.3** 
- Logic Apps Extension **v4.57.7**, Function Core tools 
- Windows 11 Enterprise **10\.0.22631 Build 22631** 

### Additional context 

*No response*

**Comment by skastberg** [comment] 2024-09-20 07:37
@Eric-B-Wu any news on this? Important with some guidance for teams to have successful work environment for Logic Apps.

**Comment by ccastrotrejo** [comment] 2024-09-23 18:00
Hi @skastberg thanks for raising this. 
- Does your scenario also fails with determining project root?
- Does the `workflow-designtime` folder gets created after opening the workspace?

**Comment by skastberg** [comment] 2024-09-23 19:34
Hi @ccastrotrejo 
If you open the the folder it fails determining the root folder, additionally the workflow-designtime is not created. If you choose to open the workspace file it works and workflow-designtime is created.

Repro can be found here https://github.com/skastberg/abc02

**Comment by ccastrotrejo** [comment] 2024-09-23 23:32
ok @skastberg, I took a look a the project structure, the reason on why just opening the folder doesn't work is because while looking for the logic apps project it doesn't look recursively across all the folders in the parent folder. 
When the project is open through the workspace file both (Functions and LogicApp) folder are in the root path. 

<img width="664" alt="image" src="https://github.com/user-attachments/assets/db4b075e-a387-4b42-870c-7a3918117d0b">

Is there any specific reason for not opening the project with the workspace file?

**Comment by skastberg** [comment] 2024-09-24 04:39
@ccastrotrejo, now that I know I open the workspace file manually. Generally, we create a repository beforehand in Azure DevOps, we have folders for documentation, pipelines and IaC for artifacts that are part of the solution. After cloning when we created the LA workspace into an existing structure, VS Code does not open the workspace but the folder.

**Comment by ccastrotrejo** [comment] 2024-09-25 17:57
Ok, so for now please keep using the workspace file, since that is the intended use and the resolution of the logic apps project is not recursive.

**Comment by ccastrotrejo** [comment] 2024-09-25 17:59
I will close this issue as duplicate of https://github.com/Azure/LogicAppsUX/issues/5458. If there is any update I will post in the other issue

**Closed by ccastrotrejo** 2024-09-25 17:59 UTC
Labels: VSCode
