### ISSUE TITLE
Select operation is converting all data types to string

### ISSUE THREAD

**Issue by Aleks-gdb** [Azure/LogicAppsUX#4110] opened 2024-02-02 22:40 UTC
### Describe the Bug with repro steps 

1. Got to new designer. 
2. Add any trigger. 
3. Add Sharepoint get items action 
4. Add select action and map Title and ID field from the Get Items action output 
5. Save the flow then run the flow and observe the outputs of the Select action are all strings even though the ID input is an integer 

### What type of Logic App Is this happening in? 

Power Automate

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

With the new designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/a5e97bdd-3b3a-4079-91b2-4f4a110400df>)

With the old designer:

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/a02caa79-3b36-4f21-a864-579dcb2f388d>)

### Browser 

Edge

### Additional context 

Note that type casting is not honored either:

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/913e4a6b-5134-4dba-b7f6-e5163c729d3d>)

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/4f93ecdb-18c3-4f96-b8e2-78d50a428b13>)

From my initial investigation the issue is that the tokens are wrapped around in {} - this does not happen in the old designer

![image](<https://github.com/Azure/LogicAppsUX/assets/42044630/23791c0b-3d28-42c0-93e2-a878b02b7949>)

**Comment by Aleks-gdb** [comment] 2024-02-03 00:57
https://github.com/Azure/LogicAppsUX/blob/3fc73e57344b41b0eafd8cef8fc3cfe45e3aacb0/libs/designer/src/lib/core/utils/parameters/helper.ts#L3326

During flow serialization, the input to the editor is treated as one array of value segments, so shouldInterpolateTokens returns true as value.length > 1 and the token gets wrapped in @{ }

![image](https://github.com/Azure/LogicAppsUX/assets/42044630/8e053220-e924-4df6-bb7b-52c6bceb282d)

**Comment by hartra344** [comment] 2024-02-05 16:54
This looks like a duplicate of #4084

**Comment by Aleks-gdb** [comment] 2024-02-05 23:06
Should be fixed with #4124

**Closed** 2024-02-08 19:28 UTC
Labels: Bug
